const fs = require('fs');

function makeTemplate(title, emoji, dateVar, kpis) {
  const kpiHtml = kpis.map(k => {
    return `<div style="flex: 1 1 0; min-width: 120px; background: ${k.bg}; border-radius: 12px; padding: 18px 12px; text-align: center; border: 1px solid ${k.border}; box-shadow: 0 1px 3px rgba(0,0,0,0.02); word-wrap: break-word;">
        <div style="font-size: 26px; font-weight: 800; color: ${k.color}; line-height: 1.1; letter-spacing: -0.5px;">${k.value}</div>
        <div style="font-size: 10px; color: #64748b; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 8px;">${k.label}</div>
      </div>`;
  }).join('\n      ');

  let html = `<div style="font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 700px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.01);">
  <div style="background: linear-gradient(135deg, #0f766e, #064e3b); padding: 40px 32px; text-align: center; position: relative;">
    <div style="position: absolute; top: 0; left: 0; right: 0; bottom: 0; opacity: 0.1; background-image: radial-gradient(#ffffff 1px, transparent 1px); background-size: 16px 16px;"></div>
    <div style="position: relative; z-index: 1;">
      <h1 style="color: white; margin: 0; font-size: 26px; font-weight: 800; letter-spacing: -0.5px;">${emoji} ${title}</h1>
      <p style="color: rgba(255,255,255,0.8); margin: 12px 0 0; font-size: 14px; font-weight: 500;">${dateVar}</p>
    </div>
  </div>
  <div style="padding: 40px 32px;">
    <div style="margin-bottom: 32px; font-size: 15px; color: #475569; line-height: 1.7; font-weight: 400;">
      {greetingMessage}
    </div>
    <div style="display: flex; flex-wrap: wrap; gap: 16px; margin-bottom: 32px;">
      ${kpiHtml}
    </div>
    {table}
  </div>
  <div style="background: #f8fafc; padding: 24px 32px; text-align: center; border-top: 1px solid #e2e8f0;">
    <p style="margin: 0; font-size: 12px; color: #64748b; font-weight: 500;">Automated update securely generated by <span style="font-weight: 700; color: #0f766e;">Paradigm FMS</span>.</p>
  </div>
</div>`;

  // Escape single quotes for SQL string literal
  return html.replace(/'/g, "''").replace(/\n/g, '');
}

const templates = [
  {
    name: 'HRM Daily Leave Summary',
    subject: 'Leave Status Report — {date}',
    title: 'Daily Leave Status Summary',
    emoji: '🌴',
    dateVar: '{date}',
    kpis: [
      { label: 'On Leave Today', value: '{totalOnLeave}', bg: '#eff6ff', border: '#bfdbfe', color: '#1e40af' },
      { label: 'Approved', value: '{approvedCount}', bg: '#f0fdf4', border: '#bbf7d0', color: '#15803d' },
      { label: 'Pending', value: '{pendingCount}', bg: '#fffbeb', border: '#fde68a', color: '#d97706' },
      { label: 'Rejected', value: '{rejectedCount}', bg: '#fef2f2', border: '#fecaca', color: '#dc2626' }
    ],
    vars: '[{"key": "date", "description": "Report date"}, {"key": "totalOnLeave", "description": "Employees on leave today"}, {"key": "approvedCount", "description": "Approved leaves"}, {"key": "pendingCount", "description": "Pending approval"}, {"key": "rejectedCount", "description": "Rejected"}, {"key": "table", "description": "Leave details table"}, {"key": "greetingMessage", "description": "Greeting message"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  },
  {
    name: 'HRM New Joiners Report',
    subject: 'New Employee Joiners — Week of {weekStart}',
    title: 'New Joiners This Week',
    emoji: '🎉',
    dateVar: 'Week Of {weekStart}',
    kpis: [
      { label: 'New Joiners', value: '{totalJoiners}', bg: '#f5f3ff', border: '#ddd6fe', color: '#5b21b6' },
      { label: 'Departments', value: '{departmentCount}', bg: '#f0fdf4', border: '#bbf7d0', color: '#15803d' },
      { label: 'Locations', value: '{locationCount}', bg: '#fff7ed', border: '#fed7aa', color: '#ea580c' }
    ],
    vars: '[{"key": "weekStart", "description": "Week start date"}, {"key": "totalJoiners", "description": "Total new joiners"}, {"key": "departmentCount", "description": "Departments"}, {"key": "locationCount", "description": "Locations"}, {"key": "table", "description": "Joiners table"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  },
  {
    name: 'HRM Pending Approvals Report',
    subject: 'Pending Approvals Summary — {date}',
    title: 'Pending Approvals — Action Required',
    emoji: '⏳',
    dateVar: '{date}',
    kpis: [
      { label: 'Leave Requests', value: '{pendingLeaves}', bg: '#fffbeb', border: '#fde68a', color: '#d97706' },
      { label: 'OT Approvals', value: '{pendingOT}', bg: '#f0f9ff', border: '#bae6fd', color: '#0284c7' },
      { label: 'Comp-Off', value: '{pendingCompOff}', bg: '#fdf2f8', border: '#f9a8d4', color: '#be185d' },
      { label: 'Total Pending', value: '{totalPending}', bg: '#fef2f2', border: '#fecaca', color: '#dc2626' }
    ],
    vars: '[{"key": "date", "description": "Report date"}, {"key": "pendingLeaves", "description": "Pending leave requests"}, {"key": "pendingOT", "description": "Pending OT"}, {"key": "pendingCompOff", "description": "Pending comp-off"}, {"key": "totalPending", "description": "Total pending"}, {"key": "table", "description": "Pending items table"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  },
  {
    name: 'HRM Payroll Snapshot',
    subject: 'Payroll Snapshot — {month} {year}',
    title: 'Payroll Snapshot',
    emoji: '💰',
    dateVar: '{month} {year}',
    kpis: [
      { label: 'Active Headcount', value: '{headcount}', bg: '#f0fdfa', border: '#99f6e4', color: '#0f766e' },
      { label: 'Est. Total Payroll', value: '₹{totalPayroll}', bg: '#f0fdf4', border: '#bbf7d0', color: '#15803d' },
      { label: 'Avg. Attendance', value: '{avgAttendance}%', bg: '#eff6ff', border: '#bfdbfe', color: '#1d4ed8' },
      { label: 'New Joiners', value: '{newJoiners}', bg: '#fff7ed', border: '#fed7aa', color: '#c2410c' }
    ],
    vars: '[{"key": "month", "description": "Payroll month"}, {"key": "year", "description": "Year"}, {"key": "headcount", "description": "Active headcount"}, {"key": "totalPayroll", "description": "Estimated payroll"}, {"key": "avgAttendance", "description": "Avg attendance %"}, {"key": "newJoiners", "description": "New joiners this month"}, {"key": "table", "description": "Department breakdown"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}]'
  },
  {
    name: 'CRM Daily Pipeline Report',
    subject: 'CRM Pipeline Snapshot — {date}',
    title: 'Daily CRM Pipeline Snapshot',
    emoji: '📊',
    dateVar: '{date}',
    kpis: [
      { label: 'Total Leads', value: '{totalLeads}', bg: '#eff6ff', border: '#bfdbfe', color: '#1e40af' },
      { label: 'Won Today', value: '{wonToday}', bg: '#f0fdf4', border: '#bbf7d0', color: '#15803d' },
      { label: 'Lost Today', value: '{lostToday}', bg: '#fef2f2', border: '#fecaca', color: '#dc2626' },
      { label: 'New Today', value: '{newToday}', bg: '#fffbeb', border: '#fde68a', color: '#d97706' }
    ],
    vars: '[{"key": "date", "description": "Report date"}, {"key": "totalLeads", "description": "Total leads"}, {"key": "wonToday", "description": "Won today"}, {"key": "lostToday", "description": "Lost today"}, {"key": "newToday", "description": "New leads today"}, {"key": "conversionRate", "description": "Conversion %"}, {"key": "table", "description": "Pipeline stage breakdown"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  },
  {
    name: 'CRM Weekly Sales Report',
    subject: 'Weekly CRM Sales Performance — {weekRange}',
    title: 'Weekly CRM Sales Performance',
    emoji: '📈',
    dateVar: 'Week: {weekRange}',
    kpis: [
      { label: 'Leads Created', value: '{leadsCreated}', bg: '#f0fdf4', border: '#bbf7d0', color: '#15803d' },
      { label: 'Stage Moves', value: '{stageMovements}', bg: '#eff6ff', border: '#bfdbfe', color: '#1e40af' },
      { label: 'Won This Week', value: '{wonThisWeek}', bg: '#fef9c3', border: '#fde047', color: '#a16207' },
      { label: 'Lost This Week', value: '{lostThisWeek}', bg: '#fef2f2', border: '#fecaca', color: '#dc2626' }
    ],
    vars: '[{"key": "weekRange", "description": "Week date range"}, {"key": "leadsCreated", "description": "Leads created this week"}, {"key": "stageMovements", "description": "Stage changes"}, {"key": "wonThisWeek", "description": "Won this week"}, {"key": "lostThisWeek", "description": "Lost this week"}, {"key": "table", "description": "Agent activity table"}, {"key": "topPerformerBadge", "description": "Top performer badge HTML"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  },
  {
    name: 'CRM Lead Aging Report',
    subject: 'Stale Lead Alert — {totalStale} Leads Aging | {date}',
    title: 'Stale & Aging Lead Alerts',
    emoji: '🔴',
    dateVar: '{date}',
    kpis: [
      { label: 'Stale Leads', value: '{totalStale}', bg: '#fef2f2', border: '#fecaca', color: '#dc2626' },
      { label: 'Avg Days in Stage', value: '{avgDaysInStage}', bg: '#fffbeb', border: '#fde68a', color: '#d97706' },
      { label: 'Oldest Lead', value: '{oldestLeadDays}', bg: '#f5f3ff', border: '#ddd6fe', color: '#5b21b6' }
    ],
    vars: '[{"key": "date", "description": "Report date"}, {"key": "totalStale", "description": "Total stale leads (30+ days)"}, {"key": "avgDaysInStage", "description": "Avg days in one stage"}, {"key": "oldestLeadDays", "description": "Oldest lead age in days"}, {"key": "table", "description": "Stale leads table sorted by age"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  },
  {
    name: 'Ops Daily Task Summary',
    subject: 'Task Summary Report — {date}',
    title: 'Daily Task Completion Summary',
    emoji: '✅',
    dateVar: '{date}',
    kpis: [
      { label: 'Total Tasks', value: '{totalTasks}', bg: '#ecfeff', border: '#a5f3fc', color: '#0e7490' },
      { label: 'Completed', value: '{completedTasks}', bg: '#f0fdf4', border: '#bbf7d0', color: '#15803d' },
      { label: 'In Progress', value: '{inProgressTasks}', bg: '#fffbeb', border: '#fde68a', color: '#d97706' },
      { label: 'Overdue', value: '{overdueTasks}', bg: '#fef2f2', border: '#fecaca', color: '#dc2626' }
    ],
    vars: '[{"key": "date", "description": "Report date"}, {"key": "totalTasks", "description": "Total tasks"}, {"key": "completedTasks", "description": "Completed tasks"}, {"key": "inProgressTasks", "description": "In-progress tasks"}, {"key": "overdueTasks", "description": "Overdue tasks"}, {"key": "table", "description": "High priority and overdue tasks table"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  },
  {
    name: 'Ops Site Activity Report',
    subject: 'Site Activity Report — {date}',
    title: 'Daily Site Activity Report',
    emoji: '📍',
    dateVar: '{date}',
    kpis: [
      { label: 'Active Sites', value: '{activeSites}', bg: '#f0fdf4', border: '#bbf7d0', color: '#15803d' },
      { label: 'Total Pings', value: '{totalPings}', bg: '#eff6ff', border: '#bfdbfe', color: '#1e40af' },
      { label: 'Field Staff Active', value: '{fieldStaffActive}', bg: '#ecfeff', border: '#a5f3fc', color: '#0e7490' },
      { label: 'Inactive Sites', value: '{inactiveSites}', bg: '#fef2f2', border: '#fecaca', color: '#dc2626' }
    ],
    vars: '[{"key": "date", "description": "Report date"}, {"key": "activeSites", "description": "Sites with activity today"}, {"key": "totalPings", "description": "Total GPS pings"}, {"key": "fieldStaffActive", "description": "Field staff checked in"}, {"key": "inactiveSites", "description": "Inactive sites"}, {"key": "table", "description": "Site-wise activity table"}, {"key": "greetingMessage", "description": "Greeting"}, {"key": "generatedTime", "description": "Generated time"}, {"key": "year", "description": "Year"}]'
  }
];

let sql = `-- NEW REPORT EMAIL TEMPLATES (Green Gradient Design)\n-- Migration: 2026-07-19\n-- 9 new report templates: 4 HRM, 3 CRM, 2 Ops\n\nINSERT INTO public.email_templates (name, subject_template, body_template, category, variables)\nVALUES\n`;

const values = templates.map((t, idx) => {
  const bodyHtml = makeTemplate(t.title, t.emoji, t.dateVar, t.kpis);
  return `-- ${idx + 1}. ${t.name}\n(\n  '${t.name}',\n  '${t.subject}',\n  '${bodyHtml}',\n  'report',\n  '${t.vars}'::jsonb\n)`;
});

sql += values.join(',\n') + '\n\nON CONFLICT DO NOTHING;\n';

fs.writeFileSync('e:/backup/onboarding all files/Paradigm Office 4/supabase/migrations/20260719_new_report_templates.sql', sql);
