import { saveAs } from 'file-saver';
import { format, startOfMonth, endOfMonth, eachDayOfInterval } from 'date-fns';
import { type EmployeeMonthlyData } from '../components/attendance/MonthlyHoursReport';
import { calculateStatsForDateRange, resolveMonthlyDayHeaders } from './attendanceCalculations';

export interface MonthlyReportRow {
    userName: string;
    statuses: string[];
    presentDays: number;
    halfDays: number;
    threeQuarterDays?: number;
    quarterDays?: number;
    absentDays: number;
    weekOffs: number;
    holidays: number;
    weekendPresents: number;
    holidayPresents: number;
    totalPayableDays: number;
    sickLeaves: number;
    earnedLeaves: number;
    compOffs: number;
    floatingHolidays: number;
    lossOfPays: number;
    workFromHomeDays: number;
    overtimeDays: number;
}

export interface LeaveBalanceRow {
    userName: string;
    earnedTotal: number;
    earnedUsed: number;
    earnedThisMonth: number;
    earnedPreviousMonth: number;
    sickTotal: number;
    sickUsed: number;
    floatingTotal: number;
    floatingUsed: number;
    compOffTotal: number;
    compOffUsed: number;
    maternityTotal: number;
    maternityUsed: number;
    childCareTotal: number;
    childCareUsed: number;
    totalBalance: number;
}

// --- Generic Excel Export ---
export interface GenericReportColumn {
    header: string;
    key: string;
    width: number;
}

export const exportGenericReportToExcel = async (
    data: any[],
    columns: GenericReportColumn[],
    reportTitle: string,
    dateRange: { startDate: Date; endDate: Date },
    fileNamePrefix: string,
    logoBase64?: string,
    generatedBy?: string
) => {
    const ExcelJS = await import('exceljs');
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet(reportTitle);

    // 1. Add Logo if available
    if (logoBase64 && logoBase64.startsWith('data:image')) {
        try {
            const base64Data = logoBase64.split(',')[1];
            const imageId = workbook.addImage({
                base64: base64Data,
                extension: 'png',
            });
            worksheet.addImage(imageId, {
                tl: { col: 0, row: 0 },
                ext: { width: 180, height: 45 }
            });
        } catch (error) {
            console.error('Failed to add logo to Excel:', error);
        }
    }

    // 2. Add Title, Date Range, and Metadata
    // Merge across all columns (or at least a sensible minimum like A-F)
    const mergeEndCol = String.fromCharCode(65 + Math.max(columns.length - 1, 5)); // A, B, C...
    
    worksheet.getRow(1).height = 35;
    worksheet.mergeCells(`A1:${mergeEndCol}1`); 
    const titleCell = worksheet.getCell('A1');
    titleCell.value = reportTitle;
    titleCell.font = { size: 16, bold: true, color: { argb: 'FF000000' } };
    titleCell.alignment = { horizontal: 'right', vertical: 'middle' };

    worksheet.getRow(2).height = 20;
    worksheet.mergeCells(`A2:${mergeEndCol}2`);
    const dateCell = worksheet.getCell('A2');
    const startStr = (dateRange.startDate instanceof Date && !isNaN(dateRange.startDate.getTime())) ? format(dateRange.startDate, 'dd MMM yyyy') : 'Start';
    const endStr = (dateRange.endDate instanceof Date && !isNaN(dateRange.endDate.getTime())) ? format(dateRange.endDate, 'dd MMM yyyy') : 'End';
    dateCell.value = `${startStr} to ${endStr}`;
    dateCell.font = { size: 11, color: { argb: 'FF444444' }, italic: true };
    dateCell.alignment = { horizontal: 'right', vertical: 'middle' };

    worksheet.getRow(3).height = 15;
    worksheet.mergeCells(`A3:${mergeEndCol}3`);
    const metaCell1 = worksheet.getCell('A3');
    metaCell1.value = `Generated: ${format(new Date(), 'dd MMM yyyy HH:mm')}`;
    metaCell1.font = { size: 10, color: { argb: 'FF666666' } };
    metaCell1.alignment = { horizontal: 'right', vertical: 'middle' };

    let currentRow = 5;

    if (generatedBy) {
        worksheet.getRow(4).height = 15;
        worksheet.mergeCells(`A4:${mergeEndCol}4`);
        const metaCell2 = worksheet.getCell('A4');
        metaCell2.value = `Generated by: ${generatedBy}`;
        metaCell2.font = { size: 10, color: { argb: 'FF666666' } };
        metaCell2.alignment = { horizontal: 'right', vertical: 'middle' };
        currentRow = 6;
    }

    // 3. Define Header Row
    const headerRow = worksheet.getRow(currentRow);
    headerRow.values = columns.map(c => c.header);
    headerRow.font = { bold: true };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    headerRow.height = 20;
    headerRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E0E0' } };
        cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
    });

    // Set widths
    columns.forEach((col, idx) => {
        worksheet.getColumn(idx + 1).width = col.width;
    });

    currentRow++;

    // 4. Add Data
    data.forEach(item => {
        const rowValues = columns.map(col => item[col.key]);
        const row = worksheet.getRow(currentRow);
        row.values = rowValues;
        
        row.eachCell((cell) => {
             cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
             cell.alignment = { wrapText: true, vertical: 'middle' };
        });
        
        currentRow++;
    });

    // 5. Generate and Save
    const buffer = await workbook.xlsx.writeBuffer();
    const monthStr = (dateRange.startDate instanceof Date && !isNaN(dateRange.startDate.getTime())) ? format(dateRange.startDate, 'MMM_yyyy') : format(new Date(), 'MMM_yyyy');
    const fileName = `${fileNamePrefix}_${monthStr}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};


// --- Existing Monthly Report Export (Optimized for Matrix Layout) ---
export const exportAttendanceToExcel = async (
    data: EmployeeMonthlyData[],
    dateRange: { startDate: Date; endDate: Date },
    logoBase64?: string,
    generatedBy?: string
) => {
    const ExcelJS = await import('exceljs');
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Monthly Attendance Report');

    // 1. Add Logo if available
    if (logoBase64 && logoBase64.startsWith('data:image')) {
        try {
            const base64Data = logoBase64.split(',')[1];
            const imageId = workbook.addImage({
                base64: base64Data,
                extension: 'png',
            });
            worksheet.addImage(imageId, {
                tl: { col: 0, row: 0 },
                ext: { width: 180, height: 45 }
            });
        } catch (error) {
            console.error('Failed to add logo to Excel:', error);
        }
    }

    // 2. Add Title & Metadata at the top
    // 2. Add Title & Metadata at the top
    worksheet.mergeCells('A1:AJ1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = 'Monthly Attendance Report';
    titleCell.font = { size: 22, bold: true, color: { argb: 'FF0D9488' } }; // Teal
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };

    worksheet.mergeCells('A2:AJ2');
    const dateCell = worksheet.getCell('A2');
    const startStr = (dateRange.startDate instanceof Date && !isNaN(dateRange.startDate.getTime())) ? format(dateRange.startDate, 'dd MMMM yyyy') : 'Start';
    const endStr = (dateRange.endDate instanceof Date && !isNaN(dateRange.endDate.getTime())) ? format(dateRange.endDate, 'dd MMMM yyyy') : 'End';
    dateCell.value = `${startStr} - ${endStr}`;
    dateCell.font = { size: 12, italic: true, color: { argb: 'FF475569' } };
    dateCell.alignment = { horizontal: 'center', vertical: 'middle' };

    let currentRow = 5;

    // 3. Loop through each employee and create a detailed block
    data.forEach((employee) => {
        // Employee Summary Header
        worksheet.mergeCells(`A${currentRow}:F${currentRow}`);
        const nameCell = worksheet.getCell(`A${currentRow}`);
        nameCell.value = employee.userName || employee.employeeName;
        nameCell.font = { bold: true, size: 14, color: { argb: 'FF1E293B' } };
        
        worksheet.mergeCells(`G${currentRow}:L${currentRow}`);
        const roleCell = worksheet.getCell(`G${currentRow}`);
        roleCell.value = `Role: ${employee.role?.replace(/_/g, ' ') || 'N/A'}`;
        roleCell.font = { italic: true, size: 11, color: { argb: 'FF64748B' } };
        
        currentRow++;

        // Status Tiles / Summary Stats Row
        const statsRow = worksheet.getRow(currentRow);
        statsRow.height = 30; // Increased height
        const stats = [
            { l: 'Net Work', v: `${(employee.totalNetWorkDuration || 0).toFixed(2)} Hrs` },
            { l: 'Total OT', v: `${(employee.totalOT || 0).toFixed(2)} Hrs` },
            { l: 'Avg Hrs', v: `${(employee.averageWorkingHrs || 0).toFixed(2)} Hrs` },
            { l: 'P', v: employee.presentDays || 0 },
            { l: 'A', v: employee.absentDays || 0 },
            { l: 'W/O', v: employee.weekOffs || 0 },
            { l: 'H', v: employee.holidays || 0 },
            { l: 'L', v: (employee.leaves || 0) },
            { l: 'Pay Days', v: employee.totalPayableDays }
        ];

        stats.forEach((s, idx) => {
            const col = idx * 2 + 1;
            // Merge Label and Value for better room
            // worksheet.mergeCells(currentRow, col, currentRow, col + 1); // We'll keep them side by side but increase labels slightly
            
            const labelCell = worksheet.getCell(currentRow, col);
            labelCell.value = s.l;
            labelCell.font = { bold: true, size: 9, color: { argb: 'FF475569' } };
            labelCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
            labelCell.alignment = { horizontal: 'center', vertical: 'middle' };
            labelCell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

            const valCell = worksheet.getCell(currentRow, col + 1);
            valCell.value = s.v;
            valCell.font = { bold: true, size: 10, color: { argb: 'FF0F172A' } };
            valCell.alignment = { horizontal: 'center', vertical: 'middle' };
            valCell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

            if (s.l === 'Pay Days') {
                valCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } };
                valCell.font.color = { argb: 'FF166534' };
            }
        });

        currentRow += 2;

        // --- Detailed 31-Day Matrix block ---
        const matrixHeaders = ['Date', ...employee.dailyData.map(d => d.date)];
        const headerRow = worksheet.getRow(currentRow);
        headerRow.values = matrixHeaders;
        headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        headerRow.height = 25;
        headerRow.eachCell((cell) => {
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF334155' } };
            cell.alignment = { horizontal: 'center', vertical: 'middle' };
            cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });
        
        // Define Rows for the matrix
        const metricsData = [
            { label: 'Status', key: 'status' },
            { label: 'In Time', key: 'inTime' },
            { label: 'Out Time', key: 'outTime' },
            { label: 'Gross', key: 'grossDuration' },
            { label: 'Net worked', key: 'netWorkedHours' },
            { label: 'OT', key: 'ot' },
            { label: 'Shift', key: 'shift' }
        ];

        metricsData.forEach((m) => {
            currentRow++;
            const rowValues = [
                m.label,
                ...employee.dailyData.map(d => {
                    const val = (d as any)[m.key];
                    if (m.key === 'shift' && typeof val === 'string') {
                        return val.replace(/Shift /g, '');
                    }
                    return val || '-';
                })
            ];
            const matrixRow = worksheet.getRow(currentRow);
            matrixRow.values = rowValues;
            matrixRow.height = 20;

            const labelCell = matrixRow.getCell(1);
            labelCell.font = { bold: true, color: { argb: 'FF1E293B' } };
            labelCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
            labelCell.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };

            for (let i = 2; i <= rowValues.length; i++) {
                const cell = matrixRow.getCell(i);
                cell.alignment = { horizontal: 'center', vertical: 'middle' };
                cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

                // Apply conditional colors for Status
                if (m.label === 'Status') {
                    const statusVal = rowValues[i - 1];
                    if (statusVal === 'P' || statusVal === 'Present' || statusVal === 'W/P' || statusVal === 'H/P' || statusVal === 'BL/P' || statusVal === 'PL/P') {
                        cell.font = { color: { argb: 'FF166534' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } };
                    } else if (statusVal === 'A' || statusVal === 'Absent' || statusVal.includes('LOP')) {
                        cell.font = { color: { argb: 'FF991B1B' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } };
                    } else if (statusVal === 'W/O') {
                        cell.font = { color: { argb: 'FF475569' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
                    } else if (statusVal === 'H') {
                        cell.font = { color: { argb: 'FF854D0E' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFef9C3' } };
                    } else if (statusVal === 'BL' || statusVal === 'F/H') {
                        cell.font = { color: { argb: 'FF1D4ED8' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDBEAFE' } };
                    } else if (statusVal === 'PL' || statusVal === 'P/L') {
                        cell.font = { color: { argb: 'FFDB2777' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFCE7F3' } };
                    } else if (['SL', 'S/L', 'EL', 'E/L', 'CL', 'C/L', 'C/O', 'ML', 'M/L', 'CC', 'W/H', 'RP', 'RC'].includes(statusVal as string) ||
                        String(statusVal).includes('SL') || String(statusVal).includes('EL') || String(statusVal).includes('CL') || String(statusVal).includes('RP') || String(statusVal).includes('RC')) {
                        cell.font = { color: { argb: 'FF4F46E5' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E7FF' } };
                    }
                }
            }
            matrixRow.getCell(1).border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });

        currentRow += 3; // Spacer between employees
    });

    // Finalize column widths
    worksheet.getColumn(1).width = 18; // Slightly wider labels
    for (let i = 2; i <= 35; i++) {
        worksheet.getColumn(i).width = 9; // Increased from 6 to 9
    }

    const buffer = await workbook.xlsx.writeBuffer();
    const monthStr = (dateRange.startDate instanceof Date && !isNaN(dateRange.startDate.getTime())) ? format(dateRange.startDate, 'MMM_yyyy') : format(new Date(), 'MMM_yyyy');
    const fileName = `Monthly_Attendance_Report_${monthStr}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};

export const exportLeaveBalancesToExcel = async (
    data: LeaveBalanceRow[],
    logoBase64?: string,
    generatedBy?: string
) => {
    const ExcelJS = await import('exceljs');
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Leave Balance Report');

    // 1. Add Logo if available
    if (logoBase64 && logoBase64.startsWith('data:image')) {
        try {
            const base64Data = logoBase64.split(',')[1];
            const imageId = workbook.addImage({
                base64: base64Data,
                extension: 'png',
            });
            worksheet.addImage(imageId, {
                tl: { col: 0, row: 0 },
                ext: { width: 180, height: 45 }
            });
        } catch (error) {
            console.error('Failed to add logo to Excel:', error);
        }
    }

    // 2. Add Title and Metadata
    worksheet.getRow(1).height = 35;
    worksheet.mergeCells('A1:P1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = 'User Leave Balance Report';
    titleCell.font = { size: 18, bold: true };
    titleCell.alignment = { horizontal: 'right', vertical: 'middle' };

    worksheet.getRow(2).height = 15;
    worksheet.mergeCells('A2:P2');
    const metaCell1 = worksheet.getCell('A2');
    metaCell1.value = `As of: ${format(new Date(), 'dd MMM yyyy HH:mm')}`;
    metaCell1.font = { size: 10, italic: true };
    metaCell1.alignment = { horizontal: 'right', vertical: 'middle' };

    if (generatedBy) {
        worksheet.getRow(3).height = 15;
        worksheet.mergeCells('A3:P3');
        const metaCell2 = worksheet.getCell('A3');
        metaCell2.value = `Generated by: ${generatedBy}`;
        metaCell2.font = { size: 10, italic: true };
        metaCell2.alignment = { horizontal: 'right', vertical: 'middle' };
    }

    let currentRow = 5;

    // 3. Define Header Row
    const columns = [
        { header: 'Employee Name', key: 'userName', width: 25 },
        { header: 'EL Earned this Month', key: 'earnedThisMonth', width: 20 },
        { header: 'EL closing Balance previous month', key: 'earnedPreviousMonth', width: 30 },
        { header: 'EL total', key: 'earnedTotal', width: 12 },
        { header: 'EL Used', key: 'earnedUsed', width: 12 },
        { header: 'SL Total', key: 'sickTotal', width: 12 },
        { header: 'SL Used', key: 'sickUsed', width: 12 },
        { header: 'FH Total', key: 'floatingTotal', width: 12 },
        { header: 'FH Used', key: 'floatingUsed', width: 12 },
        { header: 'CompOff Total', key: 'compOffTotal', width: 15 },
        { header: 'CompOff Used', key: 'compOffUsed', width: 15 },
        { header: 'Maternity Total', key: 'maternityTotal', width: 15 },
        { header: 'Maternity Used', key: 'maternityUsed', width: 15 },
        { header: 'ChildCare Total', key: 'childCareTotal', width: 15 },
        { header: 'ChildCare Used', key: 'childCareUsed', width: 15 },
        { header: 'Net Balance', key: 'totalBalance', width: 15 }
    ];

    const headerRow = worksheet.getRow(currentRow);
    headerRow.values = columns.map(c => c.header);
    headerRow.font = { bold: true };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E0E0' } };
    headerRow.alignment = { horizontal: 'center' };

    columns.forEach((col, idx) => {
        worksheet.getColumn(idx + 1).width = col.width;
    });

    currentRow++;

    // 4. Add Data
    data.forEach(item => {
        const row = worksheet.getRow(currentRow);
        row.values = columns.map(col => item[col.key as keyof LeaveBalanceRow]);
        
        // Add borders
        row.eachCell((cell) => {
            cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });
        
        currentRow++;
    });

    // 5. Generate and Save
    const buffer = await workbook.xlsx.writeBuffer();
    const fileName = `Leave_Balances_${format(new Date(), 'yyyyMMdd')}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};


export const exportMonthlyMatrixToExcel = async (
    monthlyData: Record<string, any[]>,
    dateRange: { startDate: Date; endDate: Date },
    logoBase64?: string,
    generatedBy?: string,
    generatedByRole?: string,
    targetUserName?: string,
    targetUserRole?: string,
    filters?: any,
    userHolidaysPool?: any[]
) => {
    const ExcelJS = await import('exceljs');
    const workbook = new ExcelJS.Workbook();

    // Sort month keys to ensure chronological order in sheets
    const sortedMonthKeys = Object.keys(monthlyData).sort();

    // Helper to convert 1-based column number to Excel letter (1 -> A, 27 -> AA, etc.)
    const getColLetter = (n: number) => {
        let letter = '';
        while (n > 0) {
            const temp = (n - 1) % 26;
            letter = String.fromCharCode(65 + temp) + letter;
            n = Math.floor((n - temp - 1) / 26);
        }
        return letter;
    };

    const thinBorder = {
        top: { style: 'thin' as const, color: { argb: 'FFE5E7EB' } },
        left: { style: 'thin' as const, color: { argb: 'FFE5E7EB' } },
        bottom: { style: 'thin' as const, color: { argb: 'FFE5E7EB' } },
        right: { style: 'thin' as const, color: { argb: 'FFE5E7EB' } },
    };

    for (const monthKey of sortedMonthKeys) {
        const data = monthlyData[monthKey];
        const monthDate = new Date(monthKey + '-01');
        const worksheet = workbook.addWorksheet(format(monthDate, 'MMMM yyyy'));

        // Calculate days for this month within the global range
        const monthStart = startOfMonth(monthDate);
        const monthEnd = endOfMonth(monthDate);
        const displayStart = monthStart > dateRange.startDate ? monthStart : dateRange.startDate;
        const displayEnd = monthEnd < dateRange.endDate ? monthEnd : dateRange.endDate;
        const monthDays = eachDayOfInterval({ start: displayStart, end: displayEnd });
        const maxDays = monthDays.length;

        // Recalculate employee rows using shared attendance calculation
        const recalculatedData = data.map(employee => ({
            ...employee,
            ...calculateStatsForDateRange(employee.statuses || [], monthDays)
        }));

        // Resolve exact holidays using shared algorithm (guarantees 100% match with HTML view)
        const dayHeaders = resolveMonthlyDayHeaders(monthDays, userHolidaysPool);
        const holidaysInPeriod = dayHeaders.filter(dh => dh.isHoliday);

        // Calculate Metric Summary Statistics
        const totalPresence = recalculatedData.reduce((acc, curr) => acc + (curr.presentDays || 0) + (curr.halfDays || 0) * 0.5, 0);
        const maxPossibleDays = recalculatedData.length * (monthDays.length || 30) || 1;
        const monthlyPresencePct = Math.round((totalPresence / maxPossibleDays) * 100);
        const totalPunches = Number(recalculatedData.reduce((acc, curr) => acc + (curr.presentDays || 0), 0).toFixed(2));
        const activeStaff = recalculatedData.length;

        const endColIndex = 1 + maxDays + 10; // 1 Employee + N Days + 10 Summary Stats (P, 0.5P, OT, C/O, E/L, S/L, A, W/O, H, Pay)
        const mergeEndCol = getColLetter(endColIndex);

        // --- 1. Header Block (Rows 1 to 4) ---
        if (logoBase64 && logoBase64.startsWith('data:image')) {
            try {
                const base64Data = logoBase64.split(',')[1];
                const imageId = workbook.addImage({
                    base64: base64Data,
                    extension: 'png',
                });
                worksheet.addImage(imageId, {
                    tl: { col: 0, row: 0 },
                    ext: { width: 140, height: 35 }
                });
            } catch (error) {
                console.error('Failed to add logo to Excel:', error);
            }
        }

        // Company title on left
        worksheet.mergeCells('A3:D3');
        const companyCell = worksheet.getCell('A3');
        companyCell.value = 'PARADIGM SERVICES';
        companyCell.font = { bold: true, size: 11, color: { argb: 'FF006B3F' } };
        companyCell.alignment = { horizontal: 'left', vertical: 'middle' };

        // Subtitle filter on left
        worksheet.mergeCells('A4:D4');
        const subFilterCell = worksheet.getCell('A4');
        let filterDesc = 'ALL EMPLOYEES';
        if (targetUserName) {
            filterDesc = `${targetUserName}${targetUserRole ? ` (${targetUserRole.replace(/_/g, ' ')})` : ''}`;
        } else if (filters?.site) {
            filterDesc = `Site: ${filters.site}`;
        } else if (filters?.company) {
            filterDesc = `Company: ${filters.company}`;
        }
        subFilterCell.value = filterDesc.toUpperCase();
        subFilterCell.font = { bold: true, size: 8.5, color: { argb: 'FF6B7280' } };
        subFilterCell.alignment = { horizontal: 'left', vertical: 'middle' };

        // Top-Right Report Title & Metadata
        worksheet.mergeCells(`E1:${mergeEndCol}1`);
        const titleCell = worksheet.getCell('E1');
        titleCell.value = 'MONTHLY ATTENDANCE REPORT';
        titleCell.font = { size: 18, bold: true, color: { argb: 'FF111827' } };
        titleCell.alignment = { horizontal: 'right', vertical: 'middle' };

        worksheet.mergeCells(`E2:${mergeEndCol}2`);
        const cycleCell = worksheet.getCell('E2');
        cycleCell.value = `Billing Cycle: ${format(displayStart, 'dd MMM yyyy')} - ${format(displayEnd, 'dd MMM yyyy')}`;
        cycleCell.font = { size: 11, bold: true, color: { argb: 'FF374151' } };
        cycleCell.alignment = { horizontal: 'right', vertical: 'middle' };

        worksheet.mergeCells(`E3:${mergeEndCol}3`);
        const genCell1 = worksheet.getCell('E3');
        genCell1.value = `Generated: ${format(new Date(), 'dd MMM yyyy HH:mm')}`;
        genCell1.font = { size: 9.5, color: { argb: 'FF6B7280' } };
        genCell1.alignment = { horizontal: 'right', vertical: 'middle' };

        worksheet.mergeCells(`E4:${mergeEndCol}4`);
        const genCell2 = worksheet.getCell('E4');
        genCell2.value = `By: ${generatedBy || 'Sudhan M'}${generatedByRole ? ` (${generatedByRole.toUpperCase()})` : ''}`;
        genCell2.font = { size: 9.5, color: { argb: 'FF6B7280' } };
        genCell2.alignment = { horizontal: 'right', vertical: 'middle' };

        // --- 2. Stats Cards (Rows 6 & 7) ---
        // Card 1: Monthly Presence
        worksheet.mergeCells('B6:E6');
        const pLabel = worksheet.getCell('B6');
        pLabel.value = 'MONTHLY PRESENCE';
        pLabel.font = { size: 8, bold: true, color: { argb: 'FF065F46' } };
        pLabel.alignment = { horizontal: 'center', vertical: 'middle' };
        pLabel.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FDF4' } };

        worksheet.mergeCells('B7:E7');
        const pVal = worksheet.getCell('B7');
        pVal.value = `${monthlyPresencePct}%`;
        pVal.font = { size: 16, bold: true, color: { argb: 'FF059669' } };
        pVal.alignment = { horizontal: 'center', vertical: 'middle' };
        pVal.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FDF4' } };
        pVal.border = { bottom: { style: 'medium', color: { argb: 'FF10B981' } } };

        // Card 2: Total Punches
        worksheet.mergeCells('G6:J6');
        const punchLabel = worksheet.getCell('G6');
        punchLabel.value = 'TOTAL PUNCHES';
        punchLabel.font = { size: 8, bold: true, color: { argb: 'FF1E40AF' } };
        punchLabel.alignment = { horizontal: 'center', vertical: 'middle' };
        punchLabel.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } };

        worksheet.mergeCells('G7:J7');
        const punchVal = worksheet.getCell('G7');
        punchVal.value = totalPunches;
        punchVal.font = { size: 16, bold: true, color: { argb: 'FF2563EB' } };
        punchVal.alignment = { horizontal: 'center', vertical: 'middle' };
        punchVal.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } };
        punchVal.border = { bottom: { style: 'medium', color: { argb: 'FF3B82F6' } } };

        // Card 3: Active Staff
        worksheet.mergeCells('L6:O6');
        const staffLabel = worksheet.getCell('L6');
        staffLabel.value = 'ACTIVE STAFF';
        staffLabel.font = { size: 8, bold: true, color: { argb: 'FF374151' } };
        staffLabel.alignment = { horizontal: 'center', vertical: 'middle' };
        staffLabel.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };

        worksheet.mergeCells('L7:O7');
        const staffVal = worksheet.getCell('L7');
        staffVal.value = activeStaff;
        staffVal.font = { size: 16, bold: true, color: { argb: 'FF111827' } };
        staffVal.alignment = { horizontal: 'center', vertical: 'middle' };
        staffVal.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
        staffVal.border = { bottom: { style: 'medium', color: { argb: 'FF6B7280' } } };

        let currentRow = 9;

        // --- 3. Company & Fixed Holidays Banner (Rows 9 & 10) ---
        if (holidaysInPeriod.length > 0) {
            worksheet.mergeCells(`A${currentRow}:${mergeEndCol}${currentRow}`);
            const bannerTitle = worksheet.getCell(`A${currentRow}`);
            bannerTitle.value = `📅  COMPANY & FIXED HOLIDAYS (${holidaysInPeriod.length}):`;
            bannerTitle.font = { size: 9.5, bold: true, color: { argb: 'FF881337' } };
            bannerTitle.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFE4E6' } };
            bannerTitle.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
            bannerTitle.border = { top: { style: 'thin', color: { argb: 'FFF43F5E' } }, left: { style: 'thin', color: { argb: 'FFF43F5E' } }, right: { style: 'thin', color: { argb: 'FFF43F5E' } } };

            currentRow++;
            worksheet.mergeCells(`A${currentRow}:${mergeEndCol}${currentRow}`);
            const bannerBody = worksheet.getCell(`A${currentRow}`);
            bannerBody.value = holidaysInPeriod.map(h => `• ${h.dayNumber} ${format(h.dateObj, 'MMM')} (${h.dayOfWeek}): ${h.holidayName}${h.isFixed ? ' [FIXED]' : ''}`).join('    ');
            bannerBody.font = { size: 9, bold: true, color: { argb: 'FF9F1239' } };
            bannerBody.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF1F2' } };
            bannerBody.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
            bannerBody.border = { bottom: { style: 'thin', color: { argb: 'FFF43F5E' } }, left: { style: 'thin', color: { argb: 'FFF43F5E' } }, right: { style: 'thin', color: { argb: 'FFF43F5E' } } };

            currentRow += 2; // Spacer
        } else {
            currentRow++;
        }

        // --- 4. Two-Row Matrix Header ---
        const hRow1Index = currentRow;
        const hRow2Index = currentRow + 1;

        const hRow1 = worksheet.getRow(hRow1Index);
        const hRow2 = worksheet.getRow(hRow2Index);
        hRow1.height = 22;
        hRow2.height = 18;

        // Employee Header (Merged across Row 1 & Row 2)
        worksheet.mergeCells(`A${hRow1Index}:A${hRow2Index}`);
        const empHeader = worksheet.getCell(`A${hRow1Index}`);
        empHeader.value = 'Employee';
        empHeader.font = { bold: true, size: 10, color: { argb: 'FF1F2937' } };
        empHeader.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
        empHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
        empHeader.border = thinBorder;
        worksheet.getCell(`A${hRow2Index}`).border = thinBorder;

        // Day Columns (Date Number in Row 1, Day of Week in Row 2)
        dayHeaders.forEach((dh, idx) => {
            const colNum = 2 + idx;
            const cell1 = worksheet.getCell(hRow1Index, colNum);
            const cell2 = worksheet.getCell(hRow2Index, colNum);

            cell1.value = dh.dayNumber;
            cell2.value = dh.dayOfWeek;

            cell1.alignment = { horizontal: 'center', vertical: 'middle' };
            cell2.alignment = { horizontal: 'center', vertical: 'middle' };

            if (dh.isHoliday) {
                // High-visibility rose holiday styling
                cell1.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFE4E6' } };
                cell1.font = { bold: true, size: 9.5, color: { argb: 'FF881337' } };
                cell1.border = { top: { style: 'thin', color: { argb: 'FFF43F5E' } }, left: { style: 'thin', color: { argb: 'FFF43F5E' } }, right: { style: 'thin', color: { argb: 'FFF43F5E' } }, bottom: { style: 'thin', color: { argb: 'FFF43F5E' } } };

                cell2.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFECDD3' } };
                cell2.font = { bold: true, size: 8, color: { argb: 'FF9F1239' } };
                cell2.border = { top: { style: 'thin', color: { argb: 'FFF43F5E' } }, left: { style: 'thin', color: { argb: 'FFF43F5E' } }, right: { style: 'thin', color: { argb: 'FFF43F5E' } }, bottom: { style: 'thin', color: { argb: 'FFF43F5E' } } };
            } else if (dh.isSunday) {
                // Sunday styling
                cell1.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF1F2' } };
                cell1.font = { bold: true, size: 9, color: { argb: 'FFE11D48' } };
                cell1.border = thinBorder;

                cell2.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFE4E6' } };
                cell2.font = { bold: true, size: 8, color: { argb: 'FFE11D48' } };
                cell2.border = thinBorder;
            } else {
                // Normal working day styling
                cell1.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
                cell1.font = { bold: true, size: 9, color: { argb: 'FF374151' } };
                cell1.border = thinBorder;

                cell2.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } };
                cell2.font = { size: 8, color: { argb: 'FF6B7280' } };
                cell2.border = thinBorder;
            }
        });

        // Summary Stats Column Headers (Merged across Row 1 & Row 2)
        const summaryHeaders = [
            { label: 'P', bg: 'FFD1FAE5', text: 'FF065F46' },
            { label: '0.5P', bg: 'FFDBEAFE', text: 'FF1E40AF' },
            { label: 'OT', bg: 'FFCCFBF1', text: 'FF0F766E' },
            { label: 'C/O', bg: 'FFCFFAFE', text: 'FF0E7490' },
            { label: 'E/L', bg: 'FFE0E7FF', text: 'FF3730A3' },
            { label: 'S/L', bg: 'FFF3E8FF', text: 'FF6B21A8' },
            { label: 'A', bg: 'FFFEE2E2', text: 'FF991B1B' },
            { label: 'W/O', bg: 'FFF1F5F9', text: 'FF475569' },
            { label: 'H', bg: 'FFFFEDD5', text: 'FF9A3412' },
            { label: 'Pay', bg: 'FFA7F3D0', text: 'FF064E3B' },
        ];

        summaryHeaders.forEach((sh, idx) => {
            const colNum = 2 + maxDays + idx;
            worksheet.mergeCells(hRow1Index, colNum, hRow2Index, colNum);
            const cell = worksheet.getCell(hRow1Index, colNum);
            cell.value = sh.label;
            cell.font = { bold: true, size: sh.label === 'Pay' ? 10 : 9, color: { argb: sh.text } };
            cell.alignment = { horizontal: 'center', vertical: 'middle' };
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: sh.bg } };
            cell.border = thinBorder;
            worksheet.getCell(hRow2Index, colNum).border = thinBorder;
        });

        currentRow += 2;

        // --- 5. Render Employee Data Rows ---
        recalculatedData.forEach((employee) => {
            const row = worksheet.getRow(currentRow);
            row.height = 20;

            const rowData: (string | number)[] = [employee.userName || employee.employeeName || 'Unknown'];
            const statuses = employee.statuses || [];

            monthDays.forEach((d) => {
                rowData.push(statuses[d.getDate() - 1] || '-');
            });

            rowData.push(
                employee.presentDays || 0,
                employee.halfDays || 0,
                employee.overtimeDays || 0,
                employee.compOffs || 0,
                employee.earnedLeaves || 0,
                employee.sickLeaves || 0,
                employee.absentDays || 0,
                employee.weekOffs || 0,
                employee.holidays || 0,
                employee.totalPayableDays || 0
            );

            row.values = rowData;

            // Apply conditional styling matching HTML view
            row.eachCell((cell, colNumber) => {
                cell.alignment = { horizontal: 'center', vertical: 'middle' };
                cell.border = thinBorder;

                if (colNumber === 1) {
                    cell.font = { bold: true, size: 9.5, color: { argb: 'FF111827' } };
                    cell.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
                } else if (colNumber >= 2 && colNumber <= 1 + maxDays) {
                    const dIdx = colNumber - 2;
                    const dh = dayHeaders[dIdx];
                    const s = String(cell.value || '-');
                    cell.font = { bold: true, size: 8.5 };

                    // Semantic font color
                    if (s === 'P' || s === 'Present' || s === 'H/P' || s === 'W/P' || s === 'WOP' || s === 'BL/P' || s === 'PL/P') {
                        cell.font.color = { argb: 'FF059669' }; // Present Green
                    } else if (s === 'A' || s === 'Absent') {
                        cell.font.color = { argb: 'FFDC2626' }; // Absent Red
                    } else if (s === 'W/O' || s === 'Weekly Off') {
                        cell.font.color = { argb: 'FF6B7280' }; // WO Slate
                    } else if (s === 'H' || s === 'Holiday') {
                        cell.font.color = { argb: 'FFEA580C' }; // Holiday Orange
                    } else if (s.includes('0.5')) {
                        cell.font.color = { argb: 'FF2563EB' }; // Half Day Blue
                    } else if (s.includes('OT')) {
                        cell.font.color = { argb: 'FF0D9488' }; // OT Teal
                    } else if (s.includes('C/O')) {
                        cell.font.color = { argb: 'FF0891B2' }; // Comp Cyan
                    } else if (s.includes('EL') || s.includes('E/L')) {
                        cell.font.color = { argb: 'FF4F46E5' }; // Earned Indigo
                    } else if (s.includes('SL') || s.includes('S/L')) {
                        cell.font.color = { argb: 'FF9333EA' }; // Sick Purple
                    } else if (s.includes('BL') || s.includes('F/H')) {
                        cell.font.color = { argb: 'FF1D4ED8' }; // Blue Leave
                    } else if (s.includes('PL')) {
                        cell.font.color = { argb: 'FFDB2777' }; // Pink Leave
                    } else if (s === 'W/H' || s === 'WH') {
                        cell.font.color = { argb: 'FF0D9488' }; // WFH Teal
                    } else if (s.includes('+')) {
                        cell.font.color = { argb: 'FF0D9488' }; // Combined Teal
                    } else {
                        cell.font.color = { argb: 'FF374151' };
                    }

                    // Background highlight
                    if (dh?.isHoliday) {
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF1F2' } };
                        cell.border = {
                            top: { style: 'thin', color: { argb: 'FFFECDD3' } },
                            bottom: { style: 'thin', color: { argb: 'FFFECDD3' } },
                            left: { style: 'thin', color: { argb: 'FFFECDD3' } },
                            right: { style: 'thin', color: { argb: 'FFFECDD3' } },
                        };
                    } else if (dh?.isSunday) {
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
                    } else if (s === 'A' || s === 'Absent') {
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF2F2' } };
                    }
                } else if (colNumber > 1 + maxDays) {
                    // Summary Stat Columns styling
                    const statOffset = colNumber - (2 + maxDays);
                    const sh = summaryHeaders[statOffset];
                    cell.font = { bold: true, size: 9 };

                    if (sh?.label === 'P') {
                        cell.font.color = { argb: 'FF059669' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FDF4' } };
                    } else if (sh?.label === '0.5P') {
                        cell.font.color = { argb: 'FF2563EB' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } };
                    } else if (sh?.label === 'OT') {
                        cell.font.color = { argb: 'FF0D9488' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FDFA' } };
                    } else if (sh?.label === 'C/O') {
                        cell.font.color = { argb: 'FF0891B2' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFECFEFF' } };
                    } else if (sh?.label === 'E/L') {
                        cell.font.color = { argb: 'FF4F46E5' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEEF2FF' } };
                    } else if (sh?.label === 'S/L') {
                        cell.font.color = { argb: 'FF9333EA' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFAF5FF' } };
                    } else if (sh?.label === 'A') {
                        cell.font.color = { argb: 'FFDC2626' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF2F2' } };
                    } else if (sh?.label === 'W/O') {
                        cell.font.color = { argb: 'FF6B7280' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
                    } else if (sh?.label === 'H') {
                        cell.font.color = { argb: 'FFEA580C' };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF7ED' } };
                    } else if (sh?.label === 'Pay') {
                        cell.font = { bold: true, size: 9.5, color: { argb: 'FF064E3B' } };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD1FAE5' } };
                        cell.border = {
                            top: { style: 'thin', color: { argb: 'FF10B981' } },
                            bottom: { style: 'thin', color: { argb: 'FF10B981' } },
                            left: { style: 'medium', color: { argb: 'FF10B981' } },
                            right: { style: 'thin', color: { argb: 'FF10B981' } },
                        };
                    }
                }
            });

            currentRow++;
        });

        // --- 6. Footer Notation Reference & Legend Block ---
        currentRow++;
        worksheet.mergeCells(`A${currentRow}:${mergeEndCol}${currentRow}`);
        const legendCell = worksheet.getCell(`A${currentRow}`);
        legendCell.value = 'NOTATION REFERENCE: P: Present | 0.5P: Half Day | OT: Overtime | C/O: Comp Off | E/L: Earned Leave | S/L: Sick Leave | A: Absent | W/O: Weekly Off | H: Holiday | Pay: Total Payable Days';
        legendCell.font = { size: 8.5, color: { argb: 'FF4B5563' } };
        legendCell.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
        legendCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } };
        legendCell.border = thinBorder;

        if (holidaysInPeriod.length > 0) {
            currentRow++;
            worksheet.mergeCells(`A${currentRow}:${mergeEndCol}${currentRow}`);
            const holLegendCell = worksheet.getCell(`A${currentRow}`);
            holLegendCell.value = `ROSE HIGHLIGHTED COLUMNS = Declared Company Holidays (${holidaysInPeriod.map(h => `${h.dayNumber} ${format(h.dateObj, 'MMM')}: ${h.holidayName}`).join(' • ')})`;
            holLegendCell.font = { bold: true, size: 8.5, color: { argb: 'FF881337' } };
            holLegendCell.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
            holLegendCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF1F2' } };
            holLegendCell.border = {
                top: { style: 'thin', color: { argb: 'FFFECDD3' } },
                bottom: { style: 'thin', color: { argb: 'FFFECDD3' } },
                left: { style: 'thin', color: { argb: 'FFFECDD3' } },
                right: { style: 'thin', color: { argb: 'FFFECDD3' } },
            };
        }

        // --- 7. Column Widths ---
        worksheet.getColumn(1).width = 24; // Employee column
        for (let i = 2; i <= 1 + maxDays; i++) {
            worksheet.getColumn(i).width = 5.2; // Day columns
        }
        for (let i = 2 + maxDays; i <= endColIndex - 1; i++) {
            worksheet.getColumn(i).width = 6.2; // Stats columns
        }
        worksheet.getColumn(endColIndex).width = 7.5; // Pay column
    }

    const buffer = await workbook.xlsx.writeBuffer();
    const monthStr = (dateRange.startDate instanceof Date && !isNaN(dateRange.startDate.getTime()))
        ? format(dateRange.startDate, 'MMM_yyyy')
        : format(new Date(), 'MMM_yyyy');
    const fileName = `Monthly_Attendance_Report_${monthStr}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};
