import * as ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import { format } from 'date-fns';
import { type EmployeeMonthlyData } from '../components/attendance/MonthlyHoursReport';

export interface MonthlyReportRow {
    userName: string;
    statuses: string[];
    presentDays: number;
    halfDays: number;
    threeQuarterDays?: number;
    quarterDays?: number;
    absentDays: number;
    weekOffs: number;
    holidays: number;
    weekendPresents: number;
    holidayPresents: number;
    totalPayableDays: number;
    sickLeaves: number;
    earnedLeaves: number;
    compOffs: number;
    floatingHolidays: number;
    lossOfPays: number;
    workFromHomeDays: number;
    overtimeDays: number;
}

export interface LeaveBalanceRow {
    userName: string;
    earnedTotal: number;
    earnedUsed: number;
    sickTotal: number;
    sickUsed: number;
    floatingTotal: number;
    floatingUsed: number;
    compOffTotal: number;
    compOffUsed: number;
    maternityTotal: number;
    maternityUsed: number;
    childCareTotal: number;
    childCareUsed: number;
    totalBalance: number;
}

// --- Generic Excel Export ---
export interface GenericReportColumn {
    header: string;
    key: string;
    width: number;
}

export const exportGenericReportToExcel = async (
    data: any[],
    columns: GenericReportColumn[],
    reportTitle: string,
    dateRange: { startDate: Date; endDate: Date },
    fileNamePrefix: string,
    logoBase64?: string,
    generatedBy?: string
) => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet(reportTitle);

    // 1. Add Logo if available
    if (logoBase64 && logoBase64.startsWith('data:image')) {
        try {
            const base64Data = logoBase64.split(',')[1];
            const imageId = workbook.addImage({
                base64: base64Data,
                extension: 'png',
            });
            worksheet.addImage(imageId, {
                tl: { col: 0, row: 0 },
                ext: { width: 180, height: 45 }
            });
        } catch (error) {
            console.error('Failed to add logo to Excel:', error);
        }
    }

    // 2. Add Title, Date Range, and Metadata
    // Merge across all columns (or at least a sensible minimum like A-F)
    const mergeEndCol = String.fromCharCode(65 + Math.max(columns.length - 1, 5)); // A, B, C...
    
    worksheet.getRow(1).height = 35;
    worksheet.mergeCells(`A1:${mergeEndCol}1`); 
    const titleCell = worksheet.getCell('A1');
    titleCell.value = reportTitle;
    titleCell.font = { size: 16, bold: true, color: { argb: 'FF000000' } };
    titleCell.alignment = { horizontal: 'right', vertical: 'middle' };

    worksheet.getRow(2).height = 20;
    worksheet.mergeCells(`A2:${mergeEndCol}2`);
    const dateCell = worksheet.getCell('A2');
    dateCell.value = `${format(dateRange.startDate, 'dd MMM yyyy')} to ${format(dateRange.endDate, 'dd MMM yyyy')}`;
    dateCell.font = { size: 11, color: { argb: 'FF444444' }, italic: true };
    dateCell.alignment = { horizontal: 'right', vertical: 'middle' };

    worksheet.getRow(3).height = 15;
    worksheet.mergeCells(`A3:${mergeEndCol}3`);
    const metaCell1 = worksheet.getCell('A3');
    metaCell1.value = `Generated: ${format(new Date(), 'dd MMM yyyy HH:mm')}`;
    metaCell1.font = { size: 10, color: { argb: 'FF666666' } };
    metaCell1.alignment = { horizontal: 'right', vertical: 'middle' };

    let currentRow = 5;

    if (generatedBy) {
        worksheet.getRow(4).height = 15;
        worksheet.mergeCells(`A4:${mergeEndCol}4`);
        const metaCell2 = worksheet.getCell('A4');
        metaCell2.value = `Generated by: ${generatedBy}`;
        metaCell2.font = { size: 10, color: { argb: 'FF666666' } };
        metaCell2.alignment = { horizontal: 'right', vertical: 'middle' };
        currentRow = 6;
    }

    // 3. Define Header Row
    const headerRow = worksheet.getRow(currentRow);
    headerRow.values = columns.map(c => c.header);
    headerRow.font = { bold: true };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    headerRow.height = 20;
    headerRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E0E0' } };
        cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
    });

    // Set widths
    columns.forEach((col, idx) => {
        worksheet.getColumn(idx + 1).width = col.width;
    });

    currentRow++;

    // 4. Add Data
    data.forEach(item => {
        const rowValues = columns.map(col => item[col.key]);
        const row = worksheet.getRow(currentRow);
        row.values = rowValues;
        
        row.eachCell((cell) => {
             cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
             cell.alignment = { wrapText: true, vertical: 'middle' };
        });
        
        currentRow++;
    });

    // 5. Generate and Save
    const buffer = await workbook.xlsx.writeBuffer();
    const fileName = `${fileNamePrefix}_${format(dateRange.startDate, 'MMM_yyyy')}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};


// --- Existing Monthly Report Export (Optimized for Matrix Layout) ---
export const exportAttendanceToExcel = async (
    data: EmployeeMonthlyData[],
    dateRange: { startDate: Date; endDate: Date },
    logoBase64?: string,
    generatedBy?: string
) => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Monthly Attendance Report');

    // 1. Add Logo if available
    if (logoBase64 && logoBase64.startsWith('data:image')) {
        try {
            const base64Data = logoBase64.split(',')[1];
            const imageId = workbook.addImage({
                base64: base64Data,
                extension: 'png',
            });
            worksheet.addImage(imageId, {
                tl: { col: 0, row: 0 },
                ext: { width: 180, height: 45 }
            });
        } catch (error) {
            console.error('Failed to add logo to Excel:', error);
        }
    }

    // 2. Add Title & Metadata at the top
    // 2. Add Title & Metadata at the top
    worksheet.mergeCells('A1:AJ1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = 'Monthly Attendance Report';
    titleCell.font = { size: 22, bold: true, color: { argb: 'FF0D9488' } }; // Teal
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };

    worksheet.mergeCells('A2:AJ2');
    const dateCell = worksheet.getCell('A2');
    dateCell.value = `${format(dateRange.startDate, 'dd MMMM yyyy')} - ${format(dateRange.endDate, 'dd MMMM yyyy')}`;
    dateCell.font = { size: 12, italic: true, color: { argb: 'FF475569' } };
    dateCell.alignment = { horizontal: 'center', vertical: 'middle' };

    let currentRow = 5;

    // 3. Loop through each employee and create a detailed block
    data.forEach((employee) => {
        // Employee Summary Header
        worksheet.mergeCells(`A${currentRow}:F${currentRow}`);
        const nameCell = worksheet.getCell(`A${currentRow}`);
        nameCell.value = employee.userName || employee.employeeName;
        nameCell.font = { bold: true, size: 14, color: { argb: 'FF1E293B' } };
        
        worksheet.mergeCells(`G${currentRow}:L${currentRow}`);
        const roleCell = worksheet.getCell(`G${currentRow}`);
        roleCell.value = `Role: ${employee.role?.replace(/_/g, ' ') || 'N/A'}`;
        roleCell.font = { italic: true, size: 11, color: { argb: 'FF64748B' } };
        
        currentRow++;

        // Status Tiles / Summary Stats Row
        const statsRow = worksheet.getRow(currentRow);
        statsRow.height = 30; // Increased height
        const stats = [
            { l: 'Net Work', v: `${(employee.totalNetWorkDuration || 0).toFixed(2)} Hrs` },
            { l: 'Total OT', v: `${(employee.totalOT || 0).toFixed(2)} Hrs` },
            { l: 'Avg Hrs', v: `${(employee.averageWorkingHrs || 0).toFixed(2)} Hrs` },
            { l: 'P', v: employee.presentDays || 0 },
            { l: 'A', v: employee.absentDays || 0 },
            { l: 'WO', v: employee.weekOffs || 0 },
            { l: 'H', v: employee.holidays || 0 },
            { l: 'L', v: (employee.leaves || 0) },
            { l: 'Pay Days', v: employee.totalPayableDays }
        ];

        stats.forEach((s, idx) => {
            const col = idx * 2 + 1;
            // Merge Label and Value for better room
            // worksheet.mergeCells(currentRow, col, currentRow, col + 1); // We'll keep them side by side but increase labels slightly
            
            const labelCell = worksheet.getCell(currentRow, col);
            labelCell.value = s.l;
            labelCell.font = { bold: true, size: 9, color: { argb: 'FF475569' } };
            labelCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
            labelCell.alignment = { horizontal: 'center', vertical: 'middle' };
            labelCell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

            const valCell = worksheet.getCell(currentRow, col + 1);
            valCell.value = s.v;
            valCell.font = { bold: true, size: 10, color: { argb: 'FF0F172A' } };
            valCell.alignment = { horizontal: 'center', vertical: 'middle' };
            valCell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

            if (s.l === 'Pay Days') {
                valCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } };
                valCell.font.color = { argb: 'FF166534' };
            }
        });

        currentRow += 2;

        // --- Detailed 31-Day Matrix block ---
        const matrixHeaders = ['Date', ...employee.dailyData.map(d => d.date)];
        const headerRow = worksheet.getRow(currentRow);
        headerRow.values = matrixHeaders;
        headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        headerRow.height = 25;
        headerRow.eachCell((cell) => {
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF334155' } };
            cell.alignment = { horizontal: 'center', vertical: 'middle' };
            cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });
        
        // Define Rows for the matrix
        const metricsData = [
            { label: 'Status', key: 'status' },
            { label: 'In Time', key: 'inTime' },
            { label: 'Out Time', key: 'outTime' },
            { label: 'Gross', key: 'grossDuration' },
            { label: 'Net worked', key: 'netWorkedHours' },
            { label: 'OT', key: 'ot' },
            { label: 'Shift', key: 'shift' }
        ];

        metricsData.forEach((m) => {
            currentRow++;
            const rowValues = [m.label, ...employee.dailyData.map(d => (d as any)[m.key] || '-')];
            const matrixRow = worksheet.getRow(currentRow);
            matrixRow.values = rowValues;
            matrixRow.height = 20;

            const labelCell = matrixRow.getCell(1);
            labelCell.font = { bold: true, color: { argb: 'FF1E293B' } };
            labelCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
            labelCell.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };

            for (let i = 2; i <= rowValues.length; i++) {
                const cell = matrixRow.getCell(i);
                cell.alignment = { horizontal: 'center', vertical: 'middle' };
                cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

                // Apply conditional colors for Status
                if (m.label === 'Status') {
                    const statusVal = rowValues[i - 1];
                    if (statusVal === 'P' || statusVal === 'Present' || statusVal === 'W/P' || statusVal === 'HP') {
                        cell.font = { color: { argb: 'FF166534' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } };
                    } else if (statusVal === 'A' || statusVal === 'Absent' || statusVal.includes('LOP')) {
                        cell.font = { color: { argb: 'FF991B1B' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } };
                    } else if (statusVal === 'W/O') {
                        cell.font = { color: { argb: 'FF475569' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
                    } else if (statusVal === 'H') {
                        cell.font = { color: { argb: 'FF854D0E' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFef9C3' } };
                    } else if (['L', 'S/L', 'E/L', 'C/O', 'F/H'].includes(statusVal as string)) {
                        cell.font = { color: { argb: 'FF1E40AF' }, bold: true };
                        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDBEAFE' } };
                    }
                }
            }
            matrixRow.getCell(1).border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });

        currentRow += 3; // Spacer between employees
    });

    // Finalize column widths
    worksheet.getColumn(1).width = 18; // Slightly wider labels
    for (let i = 2; i <= 35; i++) {
        worksheet.getColumn(i).width = 9; // Increased from 6 to 9
    }

    const buffer = await workbook.xlsx.writeBuffer();
    const fileName = `Monthly_Attendance_Report_${format(dateRange.startDate, 'MMM_yyyy')}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};

export const exportLeaveBalancesToExcel = async (
    data: LeaveBalanceRow[],
    logoBase64?: string,
    generatedBy?: string
) => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Leave Balance Report');

    // 1. Add Logo if available
    if (logoBase64 && logoBase64.startsWith('data:image')) {
        try {
            const base64Data = logoBase64.split(',')[1];
            const imageId = workbook.addImage({
                base64: base64Data,
                extension: 'png',
            });
            worksheet.addImage(imageId, {
                tl: { col: 0, row: 0 },
                ext: { width: 180, height: 45 }
            });
        } catch (error) {
            console.error('Failed to add logo to Excel:', error);
        }
    }

    // 2. Add Title and Metadata
    worksheet.getRow(1).height = 35;
    worksheet.mergeCells('A1:N1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = 'User Leave Balance Report';
    titleCell.font = { size: 18, bold: true };
    titleCell.alignment = { horizontal: 'right', vertical: 'middle' };

    worksheet.getRow(2).height = 15;
    worksheet.mergeCells('A2:N2');
    const metaCell1 = worksheet.getCell('A2');
    metaCell1.value = `As of: ${format(new Date(), 'dd MMM yyyy HH:mm')}`;
    metaCell1.font = { size: 10, italic: true };
    metaCell1.alignment = { horizontal: 'right', vertical: 'middle' };

    if (generatedBy) {
        worksheet.getRow(3).height = 15;
        worksheet.mergeCells('A3:N3');
        const metaCell2 = worksheet.getCell('A3');
        metaCell2.value = `Generated by: ${generatedBy}`;
        metaCell2.font = { size: 10, italic: true };
        metaCell2.alignment = { horizontal: 'right', vertical: 'middle' };
    }

    let currentRow = 5;

    // 3. Define Header Row
    const columns = [
        { header: 'Employee Name', key: 'userName', width: 25 },
        { header: 'EL Total', key: 'earnedTotal', width: 12 },
        { header: 'EL Used', key: 'earnedUsed', width: 12 },
        { header: 'SL Total', key: 'sickTotal', width: 12 },
        { header: 'SL Used', key: 'sickUsed', width: 12 },
        { header: 'FH Total', key: 'floatingTotal', width: 12 },
        { header: 'FH Used', key: 'floatingUsed', width: 12 },
        { header: 'CompOff Total', key: 'compOffTotal', width: 15 },
        { header: 'CompOff Used', key: 'compOffUsed', width: 15 },
        { header: 'Maternity Total', key: 'maternityTotal', width: 15 },
        { header: 'Maternity Used', key: 'maternityUsed', width: 15 },
        { header: 'ChildCare Total', key: 'childCareTotal', width: 15 },
        { header: 'ChildCare Used', key: 'childCareUsed', width: 15 },
        { header: 'Net Balance', key: 'totalBalance', width: 15 }
    ];

    const headerRow = worksheet.getRow(currentRow);
    headerRow.values = columns.map(c => c.header);
    headerRow.font = { bold: true };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E0E0' } };
    headerRow.alignment = { horizontal: 'center' };

    columns.forEach((col, idx) => {
        worksheet.getColumn(idx + 1).width = col.width;
    });

    currentRow++;

    // 4. Add Data
    data.forEach(item => {
        const row = worksheet.getRow(currentRow);
        row.values = columns.map(col => item[col.key as keyof LeaveBalanceRow]);
        
        // Add borders
        row.eachCell((cell) => {
            cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        });
        
        currentRow++;
    });

    // 5. Generate and Save
    const buffer = await workbook.xlsx.writeBuffer();
    const fileName = `Leave_Balances_${format(new Date(), 'yyyyMMdd')}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};


export const exportMonthlyMatrixToExcel = async (
    monthlyData: Record<string, any[]>,
    dateRange: { startDate: Date; endDate: Date },
    logoBase64?: string,
    generatedBy?: string
) => {
    const workbook = new ExcelJS.Workbook();

    // Sort month keys to ensure chronological order in sheets
    const sortedMonthKeys = Object.keys(monthlyData).sort();

    for (const monthKey of sortedMonthKeys) {
        const data = monthlyData[monthKey];
        const monthDate = new Date(monthKey + '-01'); // Ensure it's treated as start of month
        const worksheet = workbook.addWorksheet(format(monthDate, 'MMMM yyyy'));

        // 1. Add Logo if available
        if (logoBase64 && logoBase64.startsWith('data:image')) {
            try {
                const base64Data = logoBase64.split(',')[1];
                const imageId = workbook.addImage({
                    base64: base64Data,
                    extension: 'png',
                });
                worksheet.addImage(imageId, {
                    tl: { col: 0, row: 0 },
                    ext: { width: 140, height: 35 }
                });
            } catch (error) {
                console.error('Failed to add logo to Excel:', error);
            }
        }

        // Paradigm Services label
        worksheet.mergeCells('A3:E3');
        const companyCell = worksheet.getCell('A3');
        companyCell.value = 'PARADIGM SERVICES';
        companyCell.font = { bold: true, size: 9, color: { argb: 'FF9CA3AF' } };
        companyCell.alignment = { horizontal: 'left', vertical: 'middle' };

        // Get the maximum number of days to determine the last column
        const maxDays = data.length > 0 ? (data[0].statuses?.length || 31) : 31;
        const endColIndex = 1 + maxDays + 10; // Employee + Days + 10 stats columns
        
        // Helper to get column letter
        const getColLetter = (n: number) => {
            let letter = '';
            while (n > 0) {
                let temp = (n - 1) % 26;
                letter = String.fromCharCode(65 + temp) + letter;
                n = (n - temp - 1) / 26;
            }
            return letter;
        };
        const mergeEndCol = getColLetter(endColIndex);
        
        // 2. Add Title & Metadata at the top right
        worksheet.mergeCells(`F1:${mergeEndCol}1`);
        const titleCell = worksheet.getCell('F1');
        titleCell.value = 'MONTHLY ATTENDANCE REPORT';
        titleCell.font = { size: 22, bold: true, color: { argb: 'FF111827' } };
        titleCell.alignment = { horizontal: 'right', vertical: 'middle' };

        worksheet.mergeCells(`F2:${mergeEndCol}2`);
        const dateCell = worksheet.getCell('F2');
        dateCell.value = format(monthDate, 'MMMM yyyy');
        dateCell.font = { size: 12, bold: true, color: { argb: 'FF374151' } };
        dateCell.alignment = { horizontal: 'right', vertical: 'middle' };

        worksheet.mergeCells(`F3:${mergeEndCol}3`);
        const genCell1 = worksheet.getCell('F3');
        genCell1.value = `Generated: ${format(new Date(), 'dd MMM yyyy HH:mm')}`;
        genCell1.font = { size: 10, color: { argb: 'FF6B7280' } };
        genCell1.alignment = { horizontal: 'right', vertical: 'middle' };

        let currentRow = 5;
        if (generatedBy) {
            worksheet.mergeCells(`F4:${mergeEndCol}4`);
            const genCell2 = worksheet.getCell('F4');
            genCell2.value = `By: ${generatedBy}`;
            genCell2.font = { size: 10, color: { argb: 'FF6B7280' } };
            genCell2.alignment = { horizontal: 'right', vertical: 'middle' };
            currentRow = 6;
        }

        // 3. Render Matrix Header
        const headerRow = worksheet.getRow(currentRow);
        headerRow.height = 25;
        
        const headers = ['Employee'];
        for (let i = 1; i <= maxDays; i++) headers.push(i.toString());
        headers.push('P', '1/2P', 'OT', 'C/O', 'E/L', 'S/L', 'A', 'W/O', 'H', 'Pay');
        
        headerRow.values = headers;
        
        headerRow.eachCell((cell, colNumber) => {
            cell.font = { bold: true, color: { argb: 'FF374151' } };
            cell.alignment = { horizontal: 'center', vertical: 'middle' };
            cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
            
            let bgColor = 'FFF9FAFB'; // Default
            if (colNumber === 1) cell.alignment = { horizontal: 'left', vertical: 'middle' };
            
            const headerText = cell.value as string;
            if (headerText === 'P') { bgColor = 'FFD1FAE5'; cell.font.color = { argb: 'FF065F46' }; }
            else if (headerText === '1/2P') { bgColor = 'FFDBEAFE'; cell.font.color = { argb: 'FF1E40AF' }; }
            else if (headerText === 'OT') { bgColor = 'FFCCFBF1'; cell.font.color = { argb: 'FF0F766E' }; }
            else if (headerText === 'C/O') { bgColor = 'FFCFFAFE'; cell.font.color = { argb: 'FF0E7490' }; }
            else if (headerText === 'E/L') { bgColor = 'FFE0E7FF'; cell.font.color = { argb: 'FF3730A3' }; }
            else if (headerText === 'S/L') { bgColor = 'FFF3E8FF'; cell.font.color = { argb: 'FF6B21A8' }; }
            else if (headerText === 'A') { bgColor = 'FFFEE2E2'; cell.font.color = { argb: 'FF991B1B' }; }
            else if (headerText === 'H') { bgColor = 'FFFFEDD5'; cell.font.color = { argb: 'FF9A3412' }; }
            else if (headerText === 'Pay') { bgColor = 'FFD1FAE5'; cell.font.color = { argb: 'FF065F46' }; }
            
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bgColor } };
        });
        
        currentRow++;

        // 4. Render Employee Rows
        data.forEach((employee) => {
            const row = worksheet.getRow(currentRow);
            row.height = 20;
            
            const rowData = [employee.userName || employee.employeeName];
            const statuses = employee.statuses || [];
            
            for (let i = 0; i < maxDays; i++) {
                rowData.push(statuses[i] || '-');
            }
            
            rowData.push(
                employee.presentDays || 0,
                employee.halfDays || 0,
                employee.overtimeDays || 0,
                employee.compOffs || 0,
                employee.earnedLeaves || 0,
                employee.sickLeaves || 0,
                employee.absentDays || 0,
                employee.weekOffs || 0,
                employee.holidays || 0,
                employee.totalPayableDays || 0
            );
            
            row.values = rowData;
            
            row.eachCell((cell, colNumber) => {
                cell.alignment = { horizontal: 'center', vertical: 'middle' };
                cell.border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
                
                if (colNumber === 1) {
                    cell.font = { bold: true };
                    cell.alignment = { horizontal: 'left', vertical: 'middle' };
                }
                
                if (colNumber > 1 + maxDays) {
                    cell.font = { bold: true };
                    const headerText = headers[colNumber - 1];
                    if (headerText === 'P' || headerText === 'Pay') cell.font.color = { argb: 'FF059669' };
                    else if (headerText === '1/2P') cell.font.color = { argb: 'FF2563EB' };
                    else if (headerText === 'OT') cell.font.color = { argb: 'FF0D9488' };
                    else if (headerText === 'C/O') cell.font.color = { argb: 'FF0891B2' };
                    else if (headerText === 'E/L') cell.font.color = { argb: 'FF4F46E5' };
                    else if (headerText === 'S/L') cell.font.color = { argb: 'FF9333EA' };
                    else if (headerText === 'A') { cell.font.color = { argb: 'FFDC2626' }; cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } }; }
                    else if (headerText === 'H') cell.font.color = { argb: 'FFEA580C' };
                    else if (headerText === 'W/O') cell.font.color = { argb: 'FF6B7280' };
                }
                else if (colNumber > 1 && colNumber <= 1 + maxDays) {
                    const s = cell.value as string;
                    cell.font = { bold: true };
                    if (s === 'P' || s === 'Present' || s === 'HP' || s === 'H/P' || s === 'W/P' || s === 'WOP') cell.font.color = { argb: 'FF059669' };
                    else if (s === 'A' || s === 'Absent') cell.font.color = { argb: 'FFDC2626' };
                    else if (s === 'W/O' || s === 'Weekly Off') cell.font.color = { argb: 'FF64748B' };
                    else if (s === 'H' || s === 'Holiday') cell.font.color = { argb: 'FF4F46E5' };
                    else if (s.includes('S/L') || s.includes('E/L') || s.includes('C/O')) cell.font.color = { argb: 'FF7C3AED' };
                    else cell.font.color = { argb: 'FF475569' };
                }
            });
            
            currentRow++;
        });

        worksheet.getColumn(1).width = 25;
        for (let i = 2; i <= 1 + maxDays; i++) worksheet.getColumn(i).width = 5;
        for (let i = 2 + maxDays; i <= endColIndex; i++) worksheet.getColumn(i).width = 6;
    }

    const buffer = await workbook.xlsx.writeBuffer();
    const fileName = `Monthly_Attendance_Report_${format(dateRange.startDate, 'yyyy')}.xlsx`;
    saveAs(new Blob([buffer]), fileName);
};
