import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export interface PDFReportColumn {
    header: string;
    key: string;
    width?: number;
}

export interface PDFExportOptions {
    title: string;
    subtitle?: string;
    columns: PDFReportColumn[];
    data: Record<string, any>[];
    fileName: string;
    generatedBy?: string;
    orientation?: 'portrait' | 'landscape';
    statusColorMap?: Record<string, { bg: number[]; text: number[] }>;
}

const STATUS_COLORS: Record<string, { bg: number[]; text: number[] }> = {
    'APPROVED': { bg: [220, 252, 231], text: [22, 101, 52] },
    'REJECTED': { bg: [254, 226, 226], text: [153, 27, 27] },
    'PENDING MANAGER APPROVAL': { bg: [254, 249, 195], text: [133, 77, 14] },
    'PENDING HR CONFIRMATION': { bg: [219, 234, 254], text: [30, 64, 175] },
    'CANCELLED': { bg: [229, 231, 235], text: [75, 85, 99] },
    'WITHDRAWN': { bg: [229, 231, 235], text: [107, 114, 128] },
    'PENDING ADMIN CORRECTION': { bg: [224, 231, 255], text: [67, 56, 202] },
    'CORRECTION MADE': { bg: [209, 250, 229], text: [6, 95, 70] },
};

export const exportLeaveReportToPDF = (options: PDFExportOptions) => {
    const {
        title,
        subtitle,
        columns,
        data,
        fileName,
        generatedBy,
        orientation = 'landscape',
        statusColorMap = STATUS_COLORS,
    } = options;

    const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 14;

    // --- Header Section ---
    let yPos = 15;

    // Logo (Top-Left)
    const logoUrl = '/Paradigm-Logo-3-1024x157.png';
    try {
        doc.addImage(logoUrl, 'PNG', margin, 10, 45, 7);
    } catch (e) {
        console.error('Failed to load logo in PDF:', e);
    }

    // Title (Centered)
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text(title, pageWidth / 2, yPos, { align: 'center' });

    // Subtitle & Metadata (Moved to Right-Hand Side as requested)
    let metaYPos = 12;

    // Subtitle (Period)
    if (subtitle) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(80, 80, 80);
        doc.text(subtitle, pageWidth - margin, metaYPos, { align: 'right' });
        metaYPos += 6;
    }

    // Metadata line (Generated by)
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(130, 130, 130);
    const metaText = `Generated: ${format(new Date(), 'dd MMM yyyy, hh:mm a')}${generatedBy ? ` | By: ${generatedBy}` : ''}`;
    doc.text(metaText, pageWidth - margin, metaYPos, { align: 'right' });

    yPos += 14; 

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 6;

    // --- Table ---
    const tableHeaders = columns.map(c => c.header);
    const tableData = data.map(row => columns.map(col => String(row[col.key] ?? '')));

    const statusColIndex = columns.findIndex(c => c.key === 'status');

    autoTable(doc, {
        startY: yPos,
        head: [tableHeaders],
        body: tableData,
        theme: 'grid',
        styles: {
            fontSize: 8.5,
            cellPadding: 3,
            lineColor: [220, 220, 220],
            lineWidth: 0.3,
            textColor: [40, 40, 40],
            valign: 'middle',
        },
        headStyles: {
            fillColor: [45, 55, 72],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            fontSize: 9,
            halign: 'center',
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252],
        },
        columnStyles: columns.reduce((acc, col, idx) => {
            if (col.width) {
                acc[idx] = { cellWidth: col.width };
            }
            return acc;
        }, {} as Record<number, any>),
        didParseCell: (hookData: any) => {
            if (statusColIndex >= 0 && hookData.section === 'body' && hookData.column.index === statusColIndex) {
                const cellText = hookData.cell.raw?.toString().toUpperCase() || '';
                const colorConfig = statusColorMap[cellText];
                if (colorConfig) {
                    hookData.cell.styles.fillColor = colorConfig.bg;
                    hookData.cell.styles.textColor = colorConfig.text;
                    hookData.cell.styles.fontStyle = 'bold';
                }
            }
        },
        margin: { left: 14, right: 14 },
        didDrawPage: (hookData: any) => {
            // Footer
            const pageCount = (doc as any).internal.getNumberOfPages();
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(
                `Page ${hookData.pageNumber} of ${pageCount}`,
                pageWidth / 2,
                doc.internal.pageSize.getHeight() - 8,
                { align: 'center' }
            );
        },
    });

    // --- Summary at bottom ---
    const finalY = (doc as any).lastAutoTable?.finalY || yPos + 20;

    if (finalY + 20 < doc.internal.pageSize.getHeight()) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60, 60, 60);
        doc.text(`Total Records: ${data.length}`, 14, finalY + 10);
    }

    doc.save(`${fileName}.pdf`);
};
