-- ============================================================
--  CCTV Attendance Module — Database Migration
--  Run in Supabase SQL Editor
--  Adds tables for CCTV devices, logs, and enrollment queue.
--  Also adds face_embedding_512 column to public.users
-- ============================================================

-- ─── 1. cctv_devices ─────────────────────────────────────────────────────────
-- Registry of all registered CCTV edge servers / cameras.
-- Each physical site has one edge_device_id. Multiple cameras per device.
CREATE TABLE IF NOT EXISTS public.cctv_devices (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    edge_device_id      TEXT NOT NULL UNIQUE,       -- e.g. 'edge-server-site-alpha'
    device_secret       TEXT,                        -- Shared secret for auth
    organization_id     TEXT REFERENCES public.organizations(id) ON DELETE CASCADE,
    site_name           TEXT,                        -- Human-readable site name
    location_name       TEXT,                        -- Which gate/area
    cameras             JSONB DEFAULT '[]'::jsonb,  -- Camera config array
    status              TEXT DEFAULT 'offline',      -- 'online' | 'offline' | 'error'
    last_seen           TIMESTAMPTZ,
    match_threshold     FLOAT DEFAULT 0.45,
    cooldown_seconds    INTEGER DEFAULT 300,
    is_active           BOOLEAN DEFAULT TRUE,
    server_host         TEXT,                        -- Auto-detected LAN IP of edge server
    admin_port          INTEGER DEFAULT 4100,        -- Admin HTTP port for camera frames
    created_at          TIMESTAMPTZ DEFAULT now(),
    updated_at          TIMESTAMPTZ DEFAULT now()
);

-- Add columns to existing table if upgrading
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cctv_devices' AND column_name='server_host' AND table_schema='public') THEN
        ALTER TABLE public.cctv_devices ADD COLUMN server_host TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cctv_devices' AND column_name='admin_port' AND table_schema='public') THEN
        ALTER TABLE public.cctv_devices ADD COLUMN admin_port INTEGER DEFAULT 4100;
    END IF;
END $$;

-- ─── 2. cctv_attendance_logs ─────────────────────────────────────────────────
-- Raw CCTV detection log (separate from attendance_events for audit).
-- Each row is one face detection event from a CCTV camera.
CREATE TABLE IF NOT EXISTS public.cctv_attendance_logs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID REFERENCES public.users(id) ON DELETE SET NULL,
    user_name           TEXT,
    camera_name         TEXT NOT NULL,
    direction           TEXT NOT NULL CHECK (direction IN ('entry', 'exit')),
    confidence          FLOAT NOT NULL,
    detected_at         TIMESTAMPTZ NOT NULL,
    edge_device_id      TEXT,
    snapshot_url        TEXT,                        -- Supabase Storage URL for face crop
    -- Linked to the attendance_event that was created
    attendance_event_id UUID REFERENCES public.attendance_events(id) ON DELETE SET NULL,
    organization_id     TEXT,
    created_at          TIMESTAMPTZ DEFAULT now()
);

-- ─── 3. cctv_enrollment_queue ────────────────────────────────────────────────
-- Unknown faces detected by CCTV that need admin review/enrollment.
CREATE TABLE IF NOT EXISTS public.cctv_enrollment_queue (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    embedding           FLOAT[] NOT NULL,            -- 512-dim ArcFace embedding
    camera_name         TEXT NOT NULL,
    detected_at         TIMESTAMPTZ NOT NULL,
    edge_device_id      TEXT,
    snapshot_url        TEXT,
    status              TEXT DEFAULT 'pending'       -- 'pending' | 'enrolled' | 'dismissed'
                        CHECK (status IN ('pending', 'enrolled', 'dismissed')),
    resolved_by         UUID REFERENCES public.users(id) ON DELETE SET NULL,
    resolved_at         TIMESTAMPTZ,
    linked_user_id      UUID REFERENCES public.users(id) ON DELETE SET NULL,
    organization_id     TEXT,
    created_at          TIMESTAMPTZ DEFAULT now()
);

-- ─── 4. Add face_embedding_512 to users ─────────────────────────────────────
-- 512-dimensional ArcFace embedding for CCTV matching.
-- Separate from the existing 128-dim face-api.js descriptor.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users'
        AND column_name = 'face_embedding_512'
        AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.users
        ADD COLUMN face_embedding_512 FLOAT[] DEFAULT NULL;

        COMMENT ON COLUMN public.users.face_embedding_512 IS
            '512-dimensional ArcFace embedding for CCTV face recognition. '
            'Generated by InsightFace buffalo_l model. '
            'Separate from the 128-dim face_descriptor used by browser face-api.js.';
    END IF;
END $$;

-- ─── 5. Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_cctv_logs_user ON public.cctv_attendance_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_cctv_logs_detected_at ON public.cctv_attendance_logs(detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_cctv_logs_edge_device ON public.cctv_attendance_logs(edge_device_id);
CREATE INDEX IF NOT EXISTS idx_cctv_enroll_status ON public.cctv_enrollment_queue(status);
CREATE INDEX IF NOT EXISTS idx_cctv_devices_active ON public.cctv_devices(is_active);
CREATE INDEX IF NOT EXISTS idx_users_embedding ON public.users(id) WHERE face_embedding_512 IS NOT NULL;

-- ─── 6. Row Level Security ────────────────────────────────────────────────────
ALTER TABLE public.cctv_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cctv_attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cctv_enrollment_queue ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Allow public access for web app & edge servers
DROP POLICY IF EXISTS "cctv_devices_admin_only" ON public.cctv_devices;
DROP POLICY IF EXISTS "cctv_devices_public_select" ON public.cctv_devices;
DROP POLICY IF EXISTS "cctv_devices_public_insert" ON public.cctv_devices;
DROP POLICY IF EXISTS "cctv_devices_public_update" ON public.cctv_devices;
DROP POLICY IF EXISTS "cctv_devices_public_delete" ON public.cctv_devices;

CREATE POLICY "cctv_devices_public_select" ON public.cctv_devices FOR SELECT USING (true);
CREATE POLICY "cctv_devices_public_insert" ON public.cctv_devices FOR INSERT WITH CHECK (true);
CREATE POLICY "cctv_devices_public_update" ON public.cctv_devices FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "cctv_devices_public_delete" ON public.cctv_devices FOR DELETE USING (true);

DROP POLICY IF EXISTS "cctv_logs_admin_and_self" ON public.cctv_attendance_logs;
DROP POLICY IF EXISTS "cctv_logs_public_insert" ON public.cctv_attendance_logs;
DROP POLICY IF EXISTS "cctv_logs_public_select" ON public.cctv_attendance_logs;

CREATE POLICY "cctv_logs_public_insert" ON public.cctv_attendance_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "cctv_logs_public_select" ON public.cctv_attendance_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "cctv_enroll_queue_admin" ON public.cctv_enrollment_queue;
DROP POLICY IF EXISTS "cctv_enroll_queue_public" ON public.cctv_enrollment_queue;

CREATE POLICY "cctv_enroll_queue_public" ON public.cctv_enrollment_queue FOR ALL USING (true);

-- ─── 7. Updated_at trigger ───────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_cctv_devices_updated_at ON public.cctv_devices;
CREATE TRIGGER trg_cctv_devices_updated_at
    BEFORE UPDATE ON public.cctv_devices
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ─── Done ─────────────────────────────────────────────────────────────────────
DO $$
BEGIN
    RAISE NOTICE 'CCTV Attendance migration complete.';
    RAISE NOTICE 'Tables created: cctv_devices, cctv_attendance_logs, cctv_enrollment_queue';
    RAISE NOTICE 'Column added: users.face_embedding_512';
END $$;
