-- =========================================================================
-- MIGRATION: Site Responsibility & Routing Matrix Table with Mapped DB Users
-- Description: Direct relational links to public.users (UUIDs) and official names
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.site_responsibility_matrix (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    site_name TEXT NOT NULL UNIQUE,
    site_id UUID REFERENCES public.locations(id) ON DELETE SET NULL,
    organization_id TEXT,
    ops_manager_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    ops_manager_name TEXT NOT NULL,
    hr_incharge_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    hr_incharge_name TEXT NOT NULL,
    accounts_incharge_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    accounts_incharge_name TEXT NOT NULL,
    site_supervisor_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    site_supervisor_name TEXT,
    billing_company TEXT NOT NULL DEFAULT 'PIFS',
    billing_cycle TEXT DEFAULT '3rd Billing Cycle',
    units_count INTEGER,
    takeover_date DATE,
    billing_legal_name TEXT,
    buyer_address TEXT,
    voucher_type TEXT,
    gstin TEXT,
    pan TEXT,
    escalation_tiers JSONB DEFAULT '[]'::jsonb,
    routing_rules JSONB DEFAULT '{}'::jsonb,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure all columns exist on already created tables
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS organization_id TEXT;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS site_id UUID REFERENCES public.locations(id) ON DELETE SET NULL;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS ops_manager_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS hr_incharge_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS accounts_incharge_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS site_supervisor_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS site_supervisor_name TEXT;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS units_count INTEGER;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS takeover_date DATE;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS billing_legal_name TEXT;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS buyer_address TEXT;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS voucher_type TEXT;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS gstin TEXT;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS pan TEXT;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS escalation_tiers JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS routing_rules JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.site_responsibility_matrix ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

CREATE INDEX IF NOT EXISTS idx_site_resp_ops ON public.site_responsibility_matrix(ops_manager_id);
CREATE INDEX IF NOT EXISTS idx_site_resp_hr ON public.site_responsibility_matrix(hr_incharge_id);
CREATE INDEX IF NOT EXISTS idx_site_resp_accts ON public.site_responsibility_matrix(accounts_incharge_id);
CREATE INDEX IF NOT EXISTS idx_site_resp_site ON public.site_responsibility_matrix(site_id);
CREATE INDEX IF NOT EXISTS idx_site_resp_active ON public.site_responsibility_matrix(is_active);

ALTER TABLE public.site_responsibility_matrix ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated read on site_responsibility_matrix" ON public.site_responsibility_matrix;
CREATE POLICY "Allow authenticated read on site_responsibility_matrix"
    ON public.site_responsibility_matrix FOR SELECT
    TO authenticated, anon
    USING (true);

DROP POLICY IF EXISTS "Allow admin write on site_responsibility_matrix" ON public.site_responsibility_matrix;
CREATE POLICY "Allow admin write on site_responsibility_matrix"
    ON public.site_responsibility_matrix FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Seed / Upsert all active 102 sites with mapped user accounts
INSERT INTO public.site_responsibility_matrix (
    site_name,
    ops_manager_id,
    ops_manager_name,
    hr_incharge_id,
    hr_incharge_name,
    accounts_incharge_id,
    accounts_incharge_name,
    billing_company,
    billing_cycle,
    units_count,
    takeover_date,
    billing_legal_name,
    buyer_address,
    voucher_type,
    gstin,
    pan,
    escalation_tiers
) VALUES
    ('Aastha Greenhills', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 168, '2024-04-01'::date, 'Aastha Greenhills Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('ABHEE PRIDE', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 152, '2024-03-01'::date, 'ABHEE PRIDE APARTMENT OWNERS ASSOCIATION', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Anand Nilayam', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 40, '2024-05-01'::date, 'Anand Nilayam Apartment Owners Welfare Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Annciya Habitat', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 30, '2024-06-01'::date, 'Annciya Habitat Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Aratt Firenza', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 130, '2024-07-01'::date, 'Aratt Firenza Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Assetz 63 Degree East', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 688, '2024-08-01'::date, 'Assetz 63 Degree East Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Assetz Leaves & Lives', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 61, '2024-09-01'::date, 'Leaves & Lives Row House Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Assetz Marq 2.0', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 1600, '2024-10-01'::date, 'Assetz Marq 2.0 Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Astra Apartment', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 52, '2024-11-01'::date, 'Astra Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Bhumika Gardenia', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 160, '2024-12-01'::date, 'Bhumika Gardenia Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Bodhi Amrutha', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 52, '2025-01-01'::date, 'Bodhi Amrutha Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Atmosphere', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 109, '2025-02-01'::date, 'Brigade Atmosphere Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Buena Vista', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 760, '2025-03-01'::date, 'Brigade Buena Vista Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('BRIGADE CORONET', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 88, '2025-04-01'::date, 'Brigade Coronet Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Crescent', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 10, '2025-05-01'::date, 'Brigade Crescent Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Exotica', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 454, '2025-06-01'::date, 'Brigade Exotica Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Gardenia', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1000, '2025-07-01'::date, 'Brigade Gardenia Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Gateway', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1255, '2025-08-01'::date, 'Brigade Gateway Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Lakefront', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1134, '2025-09-01'::date, 'Brigade Lakefront Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Meadows Plumeria', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1848, '2025-10-01'::date, 'Plumeria at Brigade Meadows Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Millennium', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 780, '2025-11-01'::date, 'Brigade Millennium Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Omega', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 520, '2025-12-01'::date, 'Brigade Omega Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Orchards Parkside', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 156, '2026-01-01'::date, 'Parkside at Brigade Orchards Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Orchards Signature', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 288, '2026-02-01'::date, 'Signature at Brigade Orchards Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Palmsprings', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 300, '2026-03-01'::date, 'Brigade Palmsprings Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Panorama', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1035, '2026-04-01'::date, 'Brigade Panorama Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Petunia', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 56, '2026-05-01'::date, 'Brigade Petunia Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Rubix', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 350, '2026-06-01'::date, 'Brigade Rubix Commercial Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Brigade Tech Park', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 420, '2026-07-01'::date, 'Brigade Tech Park Maintenance Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Candeur Landmark', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 828, '2026-08-01'::date, 'Candeur Landmark Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Candeur Signature', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 1250, '2026-09-01'::date, 'Candeur Signature Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Casa Grand Boulevard', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 520, '2026-10-01'::date, 'Casa Grand Boulevard Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Casa Grand Lorenz', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 160, '2026-11-01'::date, 'Casa Grand Lorenz Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Chaitanya Samarth', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 180, '2026-12-01'::date, 'Chaitanya Samarth Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Concorde Amber', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 120, '2027-01-01'::date, 'Concorde Amber Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Concorde Cuppertino', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 196, '2027-02-01'::date, 'Concorde Cuppertino Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Divyasree 77 LifeStyle', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 140, '2027-03-01'::date, 'Divyasree 77 LifeStyle Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Divyasree Elan', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 380, '2027-04-01'::date, 'Divyasree Elan Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Divyasree Republic of Whitefield', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1300, '2027-05-01'::date, 'Republic of Whitefield Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Godrej Air', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 487, '2027-06-01'::date, 'Godrej Air Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Godrej Eternity', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 880, '2027-07-01'::date, 'Godrej Eternity Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Godrej Reflections', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 220, '2027-08-01'::date, 'Godrej Reflections Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Godrej United', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 516, '2027-09-01'::date, 'Godrej United Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Mantri Espana', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 438, '2027-10-01'::date, 'Mantri Espana Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Mantri Lithos', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 528, '2027-11-01'::date, 'Mantri Lithos Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Mantri Manyata Energia', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 544, '2027-12-01'::date, 'Mantri Energia Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Mantri Webcity', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1540, '2028-01-01'::date, 'Mantri Webcity Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Nikoo Homes 1', NULL, 'Isaac Roy', NULL, 'Kavya M', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 2415, '2028-02-01'::date, 'Bhartiya City Nikoo Homes 1 Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Isaac Roy","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Nikoo Homes 2', NULL, 'Isaac Roy', NULL, 'Kavya M', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1980, '2028-03-01'::date, 'Nikoo Homes 2 Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Isaac Roy","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Nikoo Homes 4', NULL, 'Isaac Roy', NULL, 'Kavya M', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1450, '2028-04-01'::date, 'Nikoo Homes 4 Maintenance Society', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Isaac Roy","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Phoenix One Bangalore West', NULL, 'Venkatachalam', NULL, 'Poojashree S', NULL, 'Sinchana KM', 'PPFMS', '1st Billing Cycle', 812, '2028-05-01'::date, 'Phoenix One Bangalore West Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Venkatachalam","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Prestige Falcon City', NULL, 'Shilpa M', NULL, 'Chandana R', NULL, 'Arya Thomas', 'PIFS', '2nd Billing Cycle', 2520, '2028-06-01'::date, 'Prestige Falcon City Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Shilpa M","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Prestige Jindal City', NULL, 'Keshav Murthy', NULL, 'Poojashree S', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 3571, '2028-07-01'::date, 'Prestige Jindal City Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Keshav Murthy","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Prestige Lakeside Habitat', NULL, 'Harish H P', NULL, 'Kavya M', NULL, 'Sinchana KM', 'PIFS', '1st Billing Cycle', 3426, '2028-08-01'::date, 'Prestige Lakeside Habitat Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Harish H P","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Prestige Park Square', NULL, 'Stany  D Souza', NULL, 'Chandana R', NULL, 'Arya Thomas', 'SWLLP', '2nd Billing Cycle', 586, '2028-09-01'::date, 'Prestige Park Square Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Stany  D Souza","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Prestige Song of the South', NULL, 'Nakul R Alvar', NULL, 'Poojashree S', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 2178, '2028-10-01'::date, 'Prestige Song of the South Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Nakul R Alvar","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Prestige Tranquility', '944263d8-c7e4-42e1-b112-cdb3b1392b44'::uuid, 'Ankur', NULL, 'Kavya M', NULL, 'Sinchana KM', 'SWLLP', '1st Billing Cycle', 2368, '2028-11-01'::date, 'Prestige Tranquility Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Ankur","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Purva Atmosphere', NULL, 'Pradeepp Gangaiah', NULL, 'Chandana R', NULL, 'Arya Thomas', 'PPFMS', '2nd Billing Cycle', 939, '2028-12-01'::date, 'Purva Atmosphere Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Pradeepp Gangaiah","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Purva Palm Beach', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1323, '2029-01-01'::date, 'Purva Palm Beach Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Purva Skydale', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 288, '2029-02-01'::date, 'Purva Skydale Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Purva Westend', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1009, '2029-03-01'::date, 'Purva Westend Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Purva Windermere', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 1800, '2029-04-01'::date, 'Purva Windermere Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Rohan Avriti', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 221, '2029-05-01'::date, 'Rohan Avriti Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Rohan Iksha', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 650, '2029-06-01'::date, 'Rohan Iksha Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Rohan Jharoka 2', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 260, '2029-07-01'::date, 'Rohan Jharoka 2 Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Rohan Upavan', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1040, '2029-08-01'::date, 'Rohan Upavan Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Rohan Viti', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 160, '2029-09-01'::date, 'Rohan Viti Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Anugraha', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1384, '2029-10-01'::date, 'Sattva Anugraha Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Cadenza', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 513, '2029-11-01'::date, 'Sattva Cadenza Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Divinity', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 824, '2029-12-01'::date, 'Sattva Divinity Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Greenage', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1676, '2030-01-01'::date, 'Salarpuria Sattva Greenage Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Laurel Heights', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 438, '2030-02-01'::date, 'Sattva Laurel Heights Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Magnificia', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 244, '2030-03-01'::date, 'Sattva Magnificia Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Mistique', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 140, '2030-04-01'::date, 'Sattva Mistique Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Navaratna', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 540, '2030-05-01'::date, 'Sattva Navaratna Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Park Cubix', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 1620, '2030-06-01'::date, 'Sattva Park Cubix Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Pipal Tree', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 550, '2030-07-01'::date, 'Sattva Pipal Tree Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Senorita', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 400, '2030-08-01'::date, 'Sattva Senorita Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Salarpuria Sattva Serene Life', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 320, '2030-09-01'::date, 'Sattva Serene Life Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Sobha City', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 2000, '2030-10-01'::date, 'Sobha City Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Sobha Dream Acres', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 6500, '2030-11-01'::date, 'Sobha Dream Acres Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Sobha HRC Pristine', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 395, '2030-12-01'::date, 'Sobha HRC Pristine Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Sobha Palm Court', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 436, '2031-01-01'::date, 'Sobha Palm Court Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Sobha Silicon Oasis', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 910, '2031-02-01'::date, 'Sobha Silicon Oasis Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Sobha Victoria Park', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 319, '2031-03-01'::date, 'Sobha Victoria Park Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Sobha Windsor', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 739, '2031-04-01'::date, 'Sobha Windsor Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment After the Rain', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 245, '2031-05-01'::date, 'After the Rain Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment In That Quiet Earth', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 560, '2031-06-01'::date, 'In That Quiet Earth Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment Learning to Fly', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 202, '2031-07-01'::date, 'Learning to Fly Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment Magic Faraway Tree', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 434, '2031-08-01'::date, 'Magic Faraway Tree Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment Pursuit of a Radical Rhapsody', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 691, '2031-09-01'::date, 'Pursuit of a Radical Rhapsody Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment The Magic Faraway Tree 2', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 200, '2031-10-01'::date, 'The Magic Faraway Tree Phase 2 Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment The Meadow Dance', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 120, '2031-11-01'::date, 'The Meadow Dance Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Total Environment Windmills of Your Mind', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 405, '2031-12-01'::date, 'Windmills of Your Mind Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Unishire Terraza', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 120, '2032-01-01'::date, 'Unishire Terraza Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Vaishnavi Commune', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 46, '2032-02-01'::date, 'Vaishnavi Commune Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Vaishnavi Gardenia', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 628, '2032-03-01'::date, 'Vaishnavi Gardenia Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Vaishnavi Oasis', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 256, '2032-04-01'::date, 'Vaishnavi Oasis Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Vaishnavi Serene', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 896, '2032-05-01'::date, 'Vaishnavi Serene Apartment Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Vaswani Reserve', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 140, '2032-06-01'::date, 'Vaswani Reserve Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('Vaswani Walbrook', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'SWLLP', '3rd Billing Cycle', 80, '2032-07-01'::date, 'Vaswani Walbrook Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb),
    ('VDB Willow Farm', NULL, 'Sandeep B', NULL, 'Chandana R', NULL, 'Arpitha Nairy', 'PIFS', '3rd Billing Cycle', 96, '2032-08-01'::date, 'VDB Willow Farm Owners Association', NULL, NULL, NULL, NULL, '[{"level":1,"role":"Site Supervisor","name":"Site In-charge","contact":"+91 80 4123 4567"},{"level":2,"role":"Operations Manager","name":"Sandeep B","contact":"Direct Ops Line"},{"level":3,"role":"Head of Operations","name":"Management Desk","contact":"support@paradigmfms.com"}]'::jsonb)
ON CONFLICT (site_name) DO UPDATE SET
    ops_manager_id = EXCLUDED.ops_manager_id,
    ops_manager_name = EXCLUDED.ops_manager_name,
    hr_incharge_id = EXCLUDED.hr_incharge_id,
    hr_incharge_name = EXCLUDED.hr_incharge_name,
    accounts_incharge_id = EXCLUDED.accounts_incharge_id,
    accounts_incharge_name = EXCLUDED.accounts_incharge_name,
    billing_company = EXCLUDED.billing_company,
    billing_cycle = EXCLUDED.billing_cycle,
    units_count = EXCLUDED.units_count,
    takeover_date = EXCLUDED.takeover_date,
    billing_legal_name = EXCLUDED.billing_legal_name,
    buyer_address = EXCLUDED.buyer_address,
    voucher_type = EXCLUDED.voucher_type,
    gstin = EXCLUDED.gstin,
    pan = EXCLUDED.pan,
    escalation_tiers = EXCLUDED.escalation_tiers,
    updated_at = NOW();
